// type: "record" = vinyl/hi-fi listening bar, "bar" = great bar worth knowing
export const BARS = [

  // BAY AREA
  { id:1,  name:"Bar Shiru", area:"bay", city:"Oakland", address:"1611 Telegraph Ave, Oakland, CA", type:"record", notes:"The godfather of the Bay Area hi-fi movement. Jazz, soul, and international grooves played in their entirety on a serious analog system. Groups of 6 or fewer only. Japanese whisky, sake, and craft cocktails. A cultural landmark.", rating:4.9, hours:"Wed–Sun 6pm–midnight", website:"https://www.barshiru.com" },
  { id:2,  name:"Harlan Records", area:"bay", city:"San Francisco", address:"75 Harlan Pl, San Francisco, CA", type:"record", notes:"Down a Union Square alley. Mid-century cocktail bar built around a vintage hi-fi system and LP collection. Slate blue benches, wood-paneled back room. Vinyl from 50s jazz to 80s new wave. Cocktails named after artists and lyrics.", rating:4.7, hours:"Tue–Sun 5pm–midnight", website:"https://www.harlanrecords.com" },
  { id:3,  name:"The Royal Cuckoo", area:"bay", city:"San Francisco", address:"3202 Mission St, San Francisco, CA", type:"record", notes:"Over a century old. A working Hammond organ played live five nights a week alongside vinyl on the turntables. Neighborhood watering hole with genuine soul. The vinyl sounds warmer here.", rating:4.7, hours:"Daily 5pm–2am", website:"" },
  { id:4,  name:"Bar Crenn", area:"bay", city:"San Francisco", address:"3131 Fillmore St, San Francisco, CA", type:"record", notes:"Dominique Crenn's most casual spot in the Fillmore. Enviable personally curated record collection on a quality system. Excellent natural wine and cocktails. The most elegant record bar in the Bay.", rating:4.7, hours:"Tue–Sat 5pm–midnight", website:"" },
  { id:5,  name:"Trick Dog", area:"bay", city:"San Francisco", address:"3010 20th St, San Francisco, CA", type:"bar", notes:"Mission District cocktail institution. Menu changes seasonally in a themed format. Consistently one of the best cocktail programs in the country.", rating:4.7, hours:"Daily 3pm–2am", website:"" },
  { id:6,  name:"Smuggler's Cove", area:"bay", city:"San Francisco", address:"650 Gough St, San Francisco, CA", type:"bar", notes:"Three-floor tiki bar with over 550 rums and the most extensive tiki cocktail menu in existence. James Beard Award-nominated. A genuine American treasure disguised as a pirate ship.", rating:4.8, hours:"Daily 5pm–1:15am", website:"https://www.smugglerscovesf.com" },
  { id:7,  name:"Heinold's First and Last Chance", area:"bay", city:"Oakland", address:"48 Webster St, Oakland, CA", type:"bar", notes:"Open since 1883. The slanting floor hasn't been repaired since the 1906 earthquake. Jack London drank here. The original bar top and fixtures are intact. The most historically important bar in Northern California.", rating:4.5, hours:"Mon–Fri 11am–9pm, Sat–Sun 10am–9pm", website:"" },

  // LOS ANGELES
  { id:8,  name:"Gold Line", area:"la", city:"Highland Park", address:"5013 York Blvd, Los Angeles, CA", type:"record", notes:"Opened by Peanut Butter Wolf of Stones Throw Records. 8,000+ discs from Wolf's personal collection behind a walnut bar. McIntosh amps, Altec Lansing speakers, Bozak rotary. Bartenders curate weeknights; guest DJs weekends. The best vinyl bar in LA.", rating:4.9, hours:"Tue–Sun 5pm–2am", website:"" },
  { id:9,  name:"Sunset & Vinyl", area:"la", city:"Hollywood", address:"6801 Hollywood Blvd, Los Angeles, CA", type:"record", notes:"Hidden inside 800 Degrees Pizza. 70s-inspired gem with crushed velvet armchairs. Guests browse the in-house collection and queue LPs for the bartender to play. Speakeasy-ish but unpretentious.", rating:4.7, hours:"Daily 5pm–midnight", website:"" },
  { id:10, name:"Grandmaster Recorders", area:"la", city:"Hollywood", address:"1518 N Cahuenga Blvd, Los Angeles, CA", type:"record", notes:"Former recording studio where Stevie Wonder, Chaka Khan, and the Chili Peppers recorded. Now a rooftop bar with regular hi-fi album listening events. Part music history, part vinyl bar.", rating:4.7, hours:"Wed–Sun 5pm–2am", website:"" },
  { id:11, name:"Wolf & Crane Bar", area:"la", city:"Los Angeles", address:"366 E 2nd St, Los Angeles, CA", type:"record", notes:"Little Tokyo izakaya-style bar with a strong vinyl program and occasional live music. Rotating DJs, great Japanese whisky selection, warm neighborhood vibe.", rating:4.6, hours:"Daily 5pm–2am", website:"" },
  { id:12, name:"The Varnish", area:"la", city:"Los Angeles", address:"118 E 6th St, Los Angeles, CA", type:"bar", notes:"Downtown LA's finest craft cocktail bar, hidden behind Cole's French Dip. Prohibition-era aesthetic, impeccable drinks, often a jazz trio. The gold standard of LA cocktail bars.", rating:4.8, hours:"Mon–Sun 7pm–2am", website:"" },
  { id:13, name:"Harvard & Stone", area:"la", city:"Los Angeles", address:"5221 Hollywood Blvd, Los Angeles, CA", type:"bar", notes:"East Hollywood rock and roll bar with one of the best live music programs in the city. Back bar hosts legendary DJ nights. Strong whiskey program. Where LA's music community actually hangs.", rating:4.6, hours:"Daily 8pm–2am", website:"" },

  // SEATTLE
  { id:14, name:"Shibuya Hi-Fi Vinyl Bar", area:"seattle", city:"Seattle", address:"5451 Leary Ave NW, Seattle, WA", type:"record", notes:"Named after the Tokyo neighborhood that inspired it. Co-owner Supreme La Rock spins from a 50,000+ personal collection — all genres, all vinyl. The Pacific Northwest's most serious listening bar.", rating:4.8, hours:"Wed–Sun 5pm–midnight", website:"" },
  { id:15, name:"Canon", area:"seattle", city:"Seattle", address:"928 12th Ave, Seattle, WA", type:"bar", notes:"Capitol Hill whiskey bar with over 4,000 bottles — one of the largest whisky selections in the world. James Beard Award-nominated. The destination for spirit obsessives in the Pacific Northwest.", rating:4.8, hours:"Daily 4pm–2am", website:"" },
  { id:16, name:"Montana Bar", area:"seattle", city:"Seattle", address:"1506 E Olive Way, Seattle, WA", type:"bar", notes:"Beloved Capitol Hill dive bar and fixture of Seattle's music community. Unpretentious, cash-friendly. The kind of bar that regulars fiercely protect.", rating:4.5, hours:"Daily 3pm–2am", website:"" },
  { id:17, name:"Rob Roy", area:"seattle", city:"Seattle", address:"2332 2nd Ave, Seattle, WA", type:"bar", notes:"Belltown craft cocktail landmark. Classic American bar program with exceptional technique. Named after the iconic cocktail. One of Seattle's most reliable bars.", rating:4.6, hours:"Daily 5pm–2am", website:"" },

  // PORTLAND
  { id:18, name:"Sonder Listening Bar", area:"portland", city:"Portland", address:"4233 NE Sandy Blvd, Portland, OR", type:"record", notes:"Portland's dedicated vinyl listening bar in the Hollywood District. Owner-DJ spins from a massive personal library on an impressive Bag End and EAW speaker rig. Dance nights and deep listening sessions.", rating:4.7, hours:"Thu–Sun 6pm–midnight", website:"" },
  { id:19, name:"Decibel Sound & Drink", area:"portland", city:"Portland", address:"4255 SE Hawthorne Blvd, Portland, OR", type:"record", notes:"Portland's first dedicated vinyl listening bar, open since 2019. Intimate hi-fi space with a thoughtful record collection and craft cocktails. Quieter and more contemplative than a typical bar.", rating:4.6, hours:"Wed–Sun 5pm–midnight", website:"" },
  { id:20, name:"Pepé le Moko", area:"portland", city:"Portland", address:"407 SW 10th Ave, Portland, OR", type:"bar", notes:"Subterranean cocktail bar beneath Ace Hotel. Art deco aesthetics, serious craft drinks, warm intimate atmosphere. A Portland institution and one of the finest cocktail bars in the Pacific Northwest.", rating:4.8, hours:"Daily 5pm–midnight", website:"" },
  { id:21, name:"Multnomah Whiskey Library", area:"portland", city:"Portland", address:"1124 SW Alder St, Portland, OR", type:"bar", notes:"Members-only whiskey library with 1,500+ bottles and a serious cocktail program. Walk-ins if space allows. The most ambitious bar program in Portland.", rating:4.7, hours:"Daily 4pm–midnight", website:"" },

  // CHICAGO
  { id:22, name:"Parachute HiFi", area:"chicago", city:"Chicago", address:"3500 N Elston Ave, Chicago, IL", type:"record", notes:"Reimagined from the James Beard Award-winning Parachute restaurant. Vinyl spun by local DJs nightly alongside inventive cocktails. Where hi-fi listening meets serious food in Chicago.", rating:4.8, hours:"Wed–Sun 5pm–midnight", website:"" },
  { id:23, name:"The Violet Hour", area:"chicago", city:"Chicago", address:"1520 N Damen Ave, Chicago, IL", type:"bar", notes:"Wicker Park cocktail landmark that helped define the modern craft cocktail movement. Unmarked door, hushed atmosphere, exceptional drinks. No cell phones. One of the most influential bars in American cocktail history.", rating:4.8, hours:"Daily 6pm–2am", website:"" },
  { id:24, name:"The Green Mill", area:"chicago", city:"Chicago", address:"4802 N Broadway, Chicago, IL", type:"bar", notes:"Open since 1907. Al Capone's booth is still there. Live jazz every single night. The Green Mill is the most important jazz bar in America — not a reproduction, the real thing.", rating:4.8, hours:"Daily 12pm–4am", website:"" },
  { id:25, name:"Billy Sunday", area:"chicago", city:"Chicago", address:"3143 W Logan Blvd, Chicago, IL", type:"bar", notes:"Logan Square cocktail bar named after the prohibition-era baseball player turned evangelist. Exceptional seasonal cocktail program, strong beer list, warm neighborhood feel.", rating:4.7, hours:"Daily 5pm–2am", website:"" },

  // NEW YORK
  { id:26, name:"Tokyo Record Bar", area:"nyc", city:"New York", address:"127 Macdougal St, New York, NY", type:"record", notes:"Each guest picks a vinyl request before sitting down — the night's playlist is built collaboratively. Only 12 seats. Prix fixe dinner. The most intimate record bar experience in NYC.", rating:4.8, hours:"Wed–Sun 6pm–midnight", website:"" },
  { id:27, name:"Public Records", area:"nyc", city:"Brooklyn", address:"233 Butler St, Brooklyn, NY", type:"record", notes:"Gowanus hi-fi record bar, performance space, vegan cafe, and record shop under one roof. One of the most distinguished sound systems available to the public. Francis Harris and partners built something genuinely special.", rating:4.8, hours:"Daily 8am–midnight", website:"https://www.public-records.com" },
  { id:28, name:"Four Horsemen", area:"nyc", city:"Brooklyn", address:"295 Grand St, Brooklyn, NY", type:"record", notes:"Created by James Murphy of LCD Soundsystem. Michelin-starred natural wine restaurant with a McIntosh-powered hi-fi system running all night. Walk-ins at the bar. One of the most famous dining and listening experiences in America.", rating:4.9, hours:"Tue–Sun 5pm–midnight", website:"" },
  { id:29, name:"Eavesdrop", area:"nyc", city:"New York", address:"108 W 13th St, New York, NY", type:"record", notes:"West Village retro studio-inspired listening bar. Prohibition-era cocktail vibes with a serious hi-fi system. Intimate and focused.", rating:4.6, hours:"Tue–Sun 5pm–midnight", website:"" },
  { id:30, name:"Attaboy", area:"nyc", city:"New York", address:"134 Eldridge St, New York, NY", type:"bar", notes:"Lower East Side speakeasy with no menu — tell the bartender what you like and they build something. Opened by the creators of Milk & Honey. One of the most influential cocktail bars in the world.", rating:4.8, hours:"Daily 6pm–4am", website:"" },
  { id:31, name:"Employees Only", area:"nyc", city:"New York", address:"510 Hudson St, New York, NY", type:"bar", notes:"West Village cocktail institution since 2004. Art deco aesthetics, psychic at the door, legendary late-night kitchen. One of the bars that defined New York's modern cocktail renaissance.", rating:4.7, hours:"Daily 6pm–4am", website:"" },

  // AUSTIN
  { id:32, name:"Equipment Room", area:"austin", city:"Austin", address:"1603 S Congress Ave, Austin, TX", type:"record", notes:"Basement of Hotel Magdalena on Music Lane. Japanese jazz kissa culture meets Austin Texas — terracotta walls, vintage concert posters, and a Klipsch La Scala system with a 1,200-strong vinyl library. The best listening bar in Texas.", rating:4.9, hours:"Wed–Sun 5pm–midnight", website:"" },
  { id:33, name:"Midnight Cowboy", area:"austin", city:"Austin", address:"313 E 6th St, Austin, TX", type:"bar", notes:"Reservations-only cocktail bar in a former brothel on 6th Street. 30-seat maximum. One of the finest cocktail programs in Texas — the antidote to Sixth Street chaos, right in the middle of it.", rating:4.8, hours:"Daily 6pm–2am", website:"" },
  { id:34, name:"The White Horse", area:"austin", city:"Austin", address:"500 Comal St, Austin, TX", type:"bar", notes:"East Austin honky-tonk with live country and Americana nightly. Two-stepping encouraged. Cold Lone Star, no pretension. The most authentic Texas bar experience in a city that sometimes forgets it's in Texas.", rating:4.6, hours:"Daily 3pm–2am", website:"" },
  { id:35, name:"Nickel City", area:"austin", city:"Austin", address:"1133 E 11th St, Austin, TX", type:"bar", notes:"East Austin dive bar with a Buffalo-inspired menu and excellent jukebox. Strong beer list, pinball machines, genuinely friendly atmosphere. One of the best dive bars in America.", rating:4.7, hours:"Daily 4pm–2am", website:"" },

  // TAIPEI
  { id:36, name:"The Tan", area:"taipei", city:"Taipei", address:"Da'an District, Taipei", type:"record", notes:"Taipei's most celebrated hi-fi listening bar. Deeply curated vinyl collection focused on jazz and soul. Custom sound system, intimate seating, serious cocktail program. The Bar Shiru of Taipei.", rating:4.8, hours:"Wed–Mon 7pm–1am", website:"" },
  { id:37, name:"Ounce Taipei", area:"taipei", city:"Taipei", address:"Da'an District, Taipei", type:"bar", notes:"Asia's 50 Best Bars honoree. Intimate reservation-only cocktail bar in Da'an. Japanese-inspired precision with Taiwanese ingredients. One of Asia's finest cocktail experiences.", rating:4.9, hours:"Tue–Sun 7pm–midnight", website:"" },
  { id:38, name:"Bar Mood", area:"taipei", city:"Taipei", address:"Zhongshan District, Taipei", type:"bar", notes:"Longstanding Taipei cocktail institution. Polished, professional bar program with a warm atmosphere. One of the city's most consistently excellent bars.", rating:4.7, hours:"Mon–Sat 6pm–2am", website:"" },

  // TOKYO
  { id:39, name:"Cafe Lion", area:"tokyo", city:"Tokyo", address:"2-19-13 Dogenzaka, Shibuya-ku, Tokyo", type:"record", notes:"Open since 1926 — the original jazz kissa where the entire listening bar concept began. Classical music only, played at high volume from two enormous speakers. No talking. No alcohol. Pure reverence. The most important music venue in Japan.", rating:4.9, hours:"Daily 11am–10:30pm", website:"" },
  { id:40, name:"Bar Martha", area:"tokyo", city:"Tokyo", address:"Ebisu, Shibuya-ku, Tokyo", type:"record", notes:"The gold standard Tokyo listening bar. Custom JBL speakers, impeccable system, delicious bar snacks. One of the bars that exported the listening bar concept globally. Reserve ahead.", rating:4.9, hours:"Wed–Mon 7pm–2am", website:"https://martha-records.com" },
  { id:41, name:"Record Bar 33 1/3rpm", area:"tokyo", city:"Tokyo", address:"Shibuya-ku, Tokyo", type:"record", notes:"Right next to Shibuya Station. Owner Shigeru stands at the turntables all night taking one request per drink order. 6,000-piece collection, rock and pop only. Cover charge, groups of 6 max.", rating:4.8, hours:"Daily 7pm–2am", website:"" },
  { id:42, name:"Studio Mule", area:"tokyo", city:"Tokyo", address:"Shibuya-ku, Tokyo", type:"record", notes:"Created by Toshiya Kawasaki of Mule Musiq. Elegant minimalist bar with Klipsch Cornwall speakers and Mark Levinson amp. Over 1,000 natural wines. The intersection of hi-fi and fine wine.", rating:4.8, hours:"Tue–Sun 6pm–midnight", website:"" },
  { id:43, name:"Ginza Music Bar", area:"tokyo", city:"Tokyo", address:"Ginza, Chuo-ku, Tokyo", type:"record", notes:"Side project of DJ Shinichi Osawa. Plush royal blue seating, Tannoy Westminster speakers. 3,000 vinyl records. Reservations recommended. The most glamorous listening bar in Tokyo.", rating:4.8, hours:"Tue–Sun 7pm–2am", website:"" },
  { id:44, name:"Star Bar Ginza", area:"tokyo", city:"Tokyo", address:"Ginza, Chuo-ku, Tokyo", type:"bar", notes:"Japan's most decorated bartender Hisashi Kishi's legendary Ginza bar. Multiple Tales of the Cocktail and Asia's 50 Best Bars awards. The pinnacle of Japanese bartending craft.", rating:4.9, hours:"Mon–Sat 5pm–midnight", website:"" },
  { id:45, name:"The SG Club", area:"tokyo", city:"Tokyo", address:"1-7-8 Jinnan, Shibuya-ku, Tokyo", type:"bar", notes:"Shibuya's two-floor cocktail institution from legendary bartender Shingo Gokan. Asia's 50 Best Bars. The most celebrated cocktail program in Tokyo.", rating:4.9, hours:"Daily 5pm–midnight", website:"" },

  // SHANGHAI
  { id:46, name:"Speak Low", area:"shanghai", city:"Shanghai", address:"579 Fuxing Zhong Lu, Shanghai", type:"bar", notes:"Shingo Gokan's Shanghai flagship — three floors, each with a different concept, hidden behind a cocktail shaker door. Asia's 50 Best Bars. The bar that put Shanghai on the global cocktail map.", rating:4.9, hours:"Daily 6pm–2am", website:"" },
  { id:47, name:"The Nest", area:"shanghai", city:"Shanghai", address:"130 Beijing Dong Lu, Shanghai", type:"record", notes:"Bund-adjacent music bar with a strong vinyl program and regular DJ events. Where Shanghai's music community gathers after hours. Deep house, jazz, and electronic sets on a quality system.", rating:4.6, hours:"Daily 8pm–4am", website:"" },
  { id:48, name:"Sober Company", area:"shanghai", city:"Shanghai", address:"Shaanxi Nan Lu, Jing'an District, Shanghai", type:"bar", notes:"One of Shanghai's most beloved cocktail bars. Multiple floors, each with a different atmosphere. Consistent Asia's 50 Best Bars presence. Serious cocktails in a beautiful space.", rating:4.8, hours:"Daily 6pm–2am", website:"" },

  // BEIJING
  { id:49, name:"El Nido", area:"beijing", city:"Beijing", address:"Sanlitun, Chaoyang District, Beijing", type:"bar", notes:"Beijing's most celebrated cocktail bar. Intimate, reservation-heavy, consistently ranked among Asia's best. The bartenders here are among the most skilled in China.", rating:4.8, hours:"Tue–Sun 7pm–2am", website:"" },
  { id:50, name:"Dusk Dawn Club", area:"beijing", city:"Beijing", address:"Gulou, Dongcheng District, Beijing", type:"record", notes:"Gulou neighborhood bar with a strong vinyl program and DJ events in the hutong area. A natural end to a day of digging in Dongcheng's record shops.", rating:4.5, hours:"Daily 7pm–2am", website:"" },
  { id:51, name:"Great Leap Brewing Hutong", area:"beijing", city:"Beijing", address:"6 Doujiao Hutong, Xicheng District, Beijing", type:"bar", notes:"The original hutong craft brewery in Beijing. Courtyard setting, excellent Beijing-brewed beers, loyal local following. The most atmospheric bar setting in the city.", rating:4.6, hours:"Daily 2pm–midnight", website:"" },

  // HONG KONG
  { id:52, name:"Potato Head Hong Kong", area:"hk", city:"Hong Kong", address:"100 Third St, Sai Ying Pun, Hong Kong", type:"record", notes:"Indonesian hi-fi hotel brand's HK outpost. A dedicated Music Room with inlaid JBL 4355 speakers, Alpha Recording System mixer, and modded Technics tables. The first audiophile bar concept in Hong Kong.", rating:4.8, hours:"Daily 12pm–midnight", website:"" },
  { id:53, name:"CNY Bar", area:"hk", city:"Hong Kong", address:"Central, Hong Kong", type:"record", notes:"Hong Kong's first dedicated audiophile bar. McIntosh-powered system with a focus on jazz, plus Cantopop and Mandopop themed nights. Signature audiophile cocktails.", rating:4.7, hours:"Tue–Sun 6pm–midnight", website:"" },
  { id:54, name:"The Old Man", area:"hk", city:"Hong Kong", address:"37 Aberdeen St, Central, Hong Kong", type:"bar", notes:"Asia's 50 Best Bars regular. Hemingway-inspired cocktail bar in Central with an inventive drinks program. One of the most celebrated cocktail experiences in Asia. Small, reservations essential.", rating:4.9, hours:"Mon–Sat 5pm–midnight", website:"" },
  { id:55, name:"Quinary", area:"hk", city:"Hong Kong", address:"56-58 Hollywood Rd, Central, Hong Kong", type:"bar", notes:"Antonio Lai's Central cocktail laboratory. Molecular techniques, exceptional flavor combinations, and a truly inventive program. One of Hong Kong's most decorated bars.", rating:4.8, hours:"Mon–Sat 5pm–midnight", website:"" },
  { id:56, name:"Foxglove", area:"hk", city:"Hong Kong", address:"6 Duddell St, Central, Hong Kong", type:"bar", notes:"Hidden behind a vintage umbrella shop, Foxglove is an art deco cocktail bar and jazz venue in Central. Live jazz nights, beautiful design. One of HK's most beautiful bars.", rating:4.7, hours:"Mon–Sat 5pm–midnight", website:"" },
];

export const BAR_AREAS = [
  { key:"all",      label:"ALL" },
  { key:"bay",      label:"BAY AREA" },
  { key:"la",       label:"LOS ANGELES" },
  { key:"seattle",  label:"SEATTLE" },
  { key:"portland", label:"PORTLAND" },
  { key:"chicago",  label:"CHICAGO" },
  { key:"nyc",      label:"NEW YORK" },
  { key:"austin",   label:"AUSTIN" },
  { key:"taipei",   label:"TAIPEI" },
  { key:"tokyo",    label:"TOKYO" },
  { key:"shanghai", label:"SHANGHAI" },
  { key:"beijing",  label:"BEIJING" },
  { key:"hk",       label:"HONG KONG" },
];

export const BAR_TYPES = [
  { key:"all",    label:"ALL" },
  { key:"record", label:"RECORD BAR" },
  { key:"bar",    label:"GREAT BAR" },
];
