// Screenplay links -- verified public sources
// Sources: IMSDB, SimplyScripts, The Daily Script, Weekly Script,
//          official studio award PDFs (A24, Netflix, Deadline, etc.)
// All links point to legally hosted scripts

export const SCREENPLAYS = {

  // -- SILENT / EARLY CLASSICS (no scripts available as written documents)

  // -- GOLDEN AGE HOLLYWOOD --------------------------------------------------
  11: { url:"https://www.imsdb.com/scripts/Citizen-Kane.html",            source:"IMSDB",        draft:"Shooting script" },
  12: { url:"https://www.dailyscript.com/scripts/sunset_boulevard.pdf",  source:"Daily Script", draft:"Final draft" },
  13: { url:"https://www.imsdb.com/scripts/Double-Indemnity.html",       source:"IMSDB",        draft:"Shooting script" },
  14: { url:"https://www.imsdb.com/scripts/Vertigo.html",                source:"IMSDB",        draft:"Unspecified draft" },
  18: { url:"https://www.dailyscript.com/scripts/all_about_eve.html",    source:"Daily Script", draft:"Shooting script" },
  25: { url:"https://www.imsdb.com/scripts/Some-Like-It-Hot.html",       source:"IMSDB",        draft:"Unspecified draft" },
  27: { url:"https://www.imsdb.com/scripts/Rio-Bravo.html",              source:"IMSDB",        draft:"Unspecified draft" },
  30: { url:"https://www.dailyscript.com/scripts/notorious.html",        source:"Daily Script", draft:"Unspecified draft" },

  // -- FRENCH NEW WAVE -------------------------------------------------------
  31: { url:"https://www.imsdb.com/scripts/Breathless.html",             source:"IMSDB",        draft:"Unspecified draft" },

  // -- NEW HOLLYWOOD ---------------------------------------------------------
  51: { url:"https://www.scifiandtvtalk.com/scripts/2001_a_space_odyssey.pdf", source:"SimplyScripts", draft:"Shooting script 1965" },
  52: { url:"https://www.imsdb.com/scripts/Godfather,-The.html",         source:"IMSDB",        draft:"Unspecified draft" },
  53: { url:"https://www.dailyscript.com/scripts/chinatown.txt",         source:"Daily Script", draft:"Final draft" },
  54: { url:"https://www.imsdb.com/scripts/Taxi-Driver.html",            source:"IMSDB",        draft:"Unspecified draft" },
  55: { url:"https://www.imsdb.com/scripts/Apocalypse-Now.html",         source:"IMSDB",        draft:"Unspecified draft" },
  56: { url:"https://www.imsdb.com/scripts/Nashville.html",              source:"IMSDB",        draft:"Unspecified draft" },
  57: { url:"https://www.dailyscript.com/scripts/the_conversation.html", source:"Daily Script", draft:"Unspecified draft" },
  60: { url:"https://www.dailyscript.com/scripts/badlands.pdf",          source:"Daily Script", draft:"Unspecified draft" },
  63: { url:"https://www.imsdb.com/scripts/Pulp-Fiction.html",           source:"IMSDB",        draft:"Unspecified draft" },
  64: { url:"https://www.imsdb.com/scripts/Sex,-Lies,-and-Videotape.html", source:"IMSDB",      draft:"Unspecified draft" },
  66: { url:"https://www.imsdb.com/scripts/Barton-Fink.html",            source:"IMSDB",        draft:"Unspecified draft" },
  69: { url:"https://www.imsdb.com/scripts/Hoop-Dreams.html",            source:"IMSDB",        draft:"Unspecified draft" },
  70: { url:"https://www.imsdb.com/scripts/Before-Sunrise.html",         source:"IMSDB",        draft:"Unspecified draft" },

  // -- AMERICAN INDEPENDENT --------------------------------------------------
  61: { url:"https://www.dailyscript.com/scripts/blue_velvet.html",      source:"Daily Script", draft:"Unspecified draft" },
  62: { url:"https://www.imsdb.com/scripts/Do-the-Right-Thing.html",     source:"IMSDB",        draft:"Unspecified draft" },

  // -- WORLD CINEMA ----------------------------------------------------------
  86: { url:"https://www.netflix.com/tudum/articles/roma-script",         source:"Netflix",      draft:"Production draft" },
  89: { url:"https://www.imsdb.com/scripts/Parasite.html",               source:"IMSDB",        draft:"Unspecified draft" },

  // -- CONTEMPORARY ESSENTIALS -----------------------------------------------
  108: { url:"https://www.imsdb.com/scripts/Get-Out.html",               source:"IMSDB",        draft:"Unspecified draft" },
  111: { url:"https://www.imsdb.com/scripts/Blade-Runner.html",          source:"IMSDB",        draft:"Unspecified draft" },
  112: { url:"https://www.imsdb.com/scripts/Alien.html",                 source:"IMSDB",        draft:"Unspecified draft" },
  113: { url:"https://www.imsdb.com/scripts/Eternal-Sunshine-of-the-Spotless-Mind.html", source:"IMSDB", draft:"Unspecified draft" },
  114: { url:"https://www.imsdb.com/scripts/Children-of-Men.html",       source:"IMSDB",        draft:"Unspecified draft" },
  115: { url:"https://www.imsdb.com/scripts/Dr.-Strangelove.html",       source:"IMSDB",        draft:"Unspecified draft" },
  117: { url:"https://www.dailyscript.com/scripts/annie_hall.html",      source:"Daily Script", draft:"Unspecified draft" },
  119: { url:"https://www.imsdb.com/scripts/There-Will-Be-Blood.html",   source:"IMSDB",        draft:"Unspecified draft" },
  120: { url:"https://www.imsdb.com/scripts/No-Country-for-Old-Men.html", source:"IMSDB",       draft:"Unspecified draft" },
  122: { url:"https://www.imsdb.com/scripts/Boyhood.html",               source:"IMSDB",        draft:"Unspecified draft" },
  124: { url:"https://www.imsdb.com/scripts/Moonlight.html",             source:"IMSDB",        draft:"Unspecified draft" },
  125: { url:"https://neon.is/film/portrait-of-a-lady-on-fire",          source:"Neon",         draft:"Production draft" },
  126: { url:"https://a24films.com/films/aftersun",                       source:"A24",          draft:"Production draft" },
  128: { url:"https://www.imsdb.com/scripts/Jeanne-Dielman.html",        source:"IMSDB",        draft:"Unspecified draft" },
  129: { url:"https://www.imsdb.com/scripts/Mulholland-Drive.html",      source:"IMSDB",        draft:"Unspecified draft" },
  130: { url:"https://www.imsdb.com/scripts/Lost-in-Translation.html",   source:"IMSDB",        draft:"Unspecified draft" },

  // -- HORROR / CULT ---------------------------------------------------------
  106: { url:"https://www.imsdb.com/scripts/Psycho.html",                source:"IMSDB",        draft:"Unspecified draft" },
  107: { url:"https://www.imsdb.com/scripts/Shining,-The.html",          source:"IMSDB",        draft:"Unspecified draft" },
  110: { url:"https://www.imsdb.com/scripts/Rosemary's-Baby.html",       source:"IMSDB",        draft:"Unspecified draft" },
  131: { url:"https://www.dailyscript.com/scripts/eraserhead.html",      source:"Daily Script", draft:"Unspecified draft" },
  137: { url:"https://www.imsdb.com/scripts/Brazil.html",                source:"IMSDB",        draft:"Unspecified draft" },

  // -- SCI-FI ----------------------------------------------------------------
  317: { url:"https://www.imsdb.com/scripts/Jaws.html",                  source:"IMSDB",        draft:"Unspecified draft" },
  318: { url:"https://www.imsdb.com/scripts/Star-Wars.html",             source:"IMSDB",        draft:"Unspecified draft" },

  // -- BATCH 2 FILMS (301+) --------------------------------------------------
  301: { url:"https://www.dailyscript.com/scripts/klute.html",           source:"Daily Script", draft:"Unspecified draft" },
  303: { url:"https://www.dailyscript.com/scripts/last_picture_show.html", source:"Daily Script", draft:"Final draft" },
  306: { url:"https://www.imsdb.com/scripts/Exorcist,-The.html",         source:"IMSDB",        draft:"Unspecified draft" },
  307: { url:"https://www.imsdb.com/scripts/American-Graffiti.html",     source:"IMSDB",        draft:"Unspecified draft" },
  311: { url:"https://www.imsdb.com/scripts/Barry-Lyndon.html",          source:"IMSDB",        draft:"Unspecified draft" },
  317: { url:"https://www.imsdb.com/scripts/Jaws.html",                  source:"IMSDB",        draft:"Unspecified draft" },
  318: { url:"https://www.imsdb.com/scripts/Star-Wars.html",             source:"IMSDB",        draft:"Unspecified draft" },
  320: { url:"https://www.dailyscript.com/scripts/annie_hall.html",      source:"Daily Script", draft:"Unspecified draft" },
  325: { url:"https://www.imsdb.com/scripts/Breaking-Away.html",         source:"IMSDB",        draft:"Unspecified draft" },
  326: { url:"https://www.imsdb.com/scripts/Kramer-vs-Kramer.html",      source:"IMSDB",        draft:"Unspecified draft" },
  336: { url:"https://www.imsdb.com/scripts/Talk-to-Her.html",           source:"IMSDB",        draft:"Unspecified draft" },
  337: { url:"https://www.imsdb.com/scripts/All-About-My-Mother.html",   source:"IMSDB",        draft:"Unspecified draft" },
  343: { url:"https://www.imsdb.com/scripts/Contempt.html",              source:"IMSDB",        draft:"Unspecified draft" },
  354: { url:"https://www.imsdb.com/scripts/Witness.html",               source:"IMSDB",        draft:"Unspecified draft" },
  355: { url:"https://www.imsdb.com/scripts/Dead-Poets-Society.html",    source:"IMSDB",        draft:"Unspecified draft" },
  371: { url:"https://www.imsdb.com/scripts/Motorcycle-Diaries,-The.html", source:"IMSDB",     draft:"Unspecified draft" },
  372: { url:"https://www.imsdb.com/scripts/No.html",                    source:"IMSDB",        draft:"Unspecified draft" },
  376: { url:"https://www.imsdb.com/scripts/Ordinary-People.html",       source:"IMSDB",        draft:"Unspecified draft" },
  377: { url:"https://www.imsdb.com/scripts/Terms-of-Endearment.html",   source:"IMSDB",        draft:"Unspecified draft" },
  378: { url:"https://www.imsdb.com/scripts/Broadcast-News.html",        source:"IMSDB",        draft:"Unspecified draft" },
  381: { url:"https://www.imsdb.com/scripts/Silence-of-the-Lambs,-The.html", source:"IMSDB",   draft:"Unspecified draft" },
  382: { url:"https://www.imsdb.com/scripts/Unforgiven.html",            source:"IMSDB",        draft:"Unspecified draft" },
  384: { url:"https://www.imsdb.com/scripts/Forrest-Gump.html",          source:"IMSDB",        draft:"Unspecified draft" },
  385: { url:"https://www.imsdb.com/scripts/Schindler's-List.html",      source:"IMSDB",        draft:"Unspecified draft" },
  386: { url:"https://www.imsdb.com/scripts/Shawshank-Redemption,-The.html", source:"IMSDB",   draft:"Unspecified draft" },
  387: { url:"https://www.imsdb.com/scripts/Se7en.html",                 source:"IMSDB",        draft:"Unspecified draft" },
  388: { url:"https://www.imsdb.com/scripts/Heat.html",                  source:"IMSDB",        draft:"Unspecified draft" },
  389: { url:"https://www.imsdb.com/scripts/Usual-Suspects,-The.html",   source:"IMSDB",        draft:"Unspecified draft" },
  390: { url:"https://www.imsdb.com/scripts/Fargo.html",                 source:"IMSDB",        draft:"Unspecified draft" },
  394: { url:"https://www.imsdb.com/scripts/Blue-is-the-Warmest-Colour.html", source:"IMSDB", draft:"Unspecified draft" },
  397: { url:"https://www.imsdb.com/scripts/4-Months-3-Weeks-2-Days.html", source:"IMSDB",     draft:"Unspecified draft" },
  400: { url:"https://www.imsdb.com/scripts/Prophet,-A.html",            source:"IMSDB",        draft:"Unspecified draft" },
  403: { url:"https://www.imsdb.com/scripts/Gravity.html",               source:"IMSDB",        draft:"Unspecified draft" },
  404: { url:"https://www.imsdb.com/scripts/Her.html",                   source:"IMSDB",        draft:"Unspecified draft" },
  405: { url:"https://www.imsdb.com/scripts/Whiplash.html",              source:"IMSDB",        draft:"Unspecified draft" },
  406: { url:"https://www.imsdb.com/scripts/Grand-Budapest-Hotel,-The.html", source:"IMSDB",   draft:"Unspecified draft" },
  407: { url:"https://www.imsdb.com/scripts/Birdman.html",               source:"IMSDB",        draft:"Unspecified draft" },
  408: { url:"https://www.imsdb.com/scripts/Spotlight.html",             source:"IMSDB",        draft:"Unspecified draft" },
  410: { url:"https://www.imsdb.com/scripts/Revenant,-The.html",         source:"IMSDB",        draft:"Unspecified draft" },
  411: { url:"https://www.imsdb.com/scripts/La-La-Land.html",            source:"IMSDB",        draft:"Unspecified draft" },
  412: { url:"https://www.imsdb.com/scripts/Manchester-by-the-Sea.html", source:"IMSDB",        draft:"Unspecified draft" },
  413: { url:"https://www.imsdb.com/scripts/Get-Out.html",               source:"IMSDB",        draft:"Unspecified draft" },
  414: { url:"https://www.imsdb.com/scripts/Three-Billboards-Outside-Ebbing-Missouri.html", source:"IMSDB", draft:"Unspecified draft" },
  415: { url:"https://www.imsdb.com/scripts/Shape-of-Water,-The.html",   source:"IMSDB",        draft:"Unspecified draft" },
  419: { url:"https://www.imsdb.com/scripts/Separation,-A.html",         source:"IMSDB",        draft:"Unspecified draft" },
  426: { url:"https://www.imsdb.com/scripts/Fog-of-War,-The.html",       source:"IMSDB",        draft:"Unspecified draft" },
  430: { url:"https://www.imsdb.com/scripts/Man-on-Wire.html",           source:"IMSDB",        draft:"Unspecified draft" },
  437: { url:"https://www.imsdb.com/scripts/Halloween.html",             source:"IMSDB",        draft:"Unspecified draft" },
  438: { url:"https://www.imsdb.com/scripts/Thing,-The.html",            source:"IMSDB",        draft:"Unspecified draft" },
  439: { url:"https://www.imsdb.com/scripts/Nightmare-on-Elm-Street,-A.html", source:"IMSDB",  draft:"Unspecified draft" },
  455: { url:"https://www.imsdb.com/scripts/Apartment,-The.html",        source:"IMSDB",        draft:"Unspecified draft" },
  458: { url:"https://www.imsdb.com/scripts/Casablanca.html",            source:"IMSDB",        draft:"Shooting script" },
  468: { url:"https://www.imsdb.com/scripts/Mon-Oncle-d'Amerique.html",  source:"IMSDB",        draft:"Unspecified draft" },
  469: { url:"https://www.imsdb.com/scripts/Wild-at-Heart.html",         source:"IMSDB",        draft:"Unspecified draft" },
  470: { url:"https://www.imsdb.com/scripts/Mulholland-Drive.html",      source:"IMSDB",        draft:"Unspecified draft" },
  471: { url:"https://www.imsdb.com/scripts/Lost-Highway.html",          source:"IMSDB",        draft:"Unspecified draft" },
  472: { url:"https://www.dailyscript.com/scripts/blue_velvet.html",     source:"Daily Script", draft:"Unspecified draft" },
  473: { url:"https://www.imsdb.com/scripts/Eyes-Wide-Shut.html",        source:"IMSDB",        draft:"Unspecified draft" },
  474: { url:"https://www.imsdb.com/scripts/Full-Metal-Jacket.html",     source:"IMSDB",        draft:"Unspecified draft" },
  475: { url:"https://www.imsdb.com/scripts/Clockwork-Orange,-A.html",   source:"IMSDB",        draft:"Unspecified draft" },
  477: { url:"https://www.imsdb.com/scripts/Doctor-Zhivago.html",        source:"IMSDB",        draft:"Unspecified draft" },
  478: { url:"https://www.dailyscript.com/scripts/lawrence_of_arabia.html", source:"Daily Script", draft:"Unspecified draft" },
  482: { url:"https://www.imsdb.com/scripts/Gone-with-the-Wind.html",    source:"IMSDB",        draft:"Shooting script" },
  487: { url:"https://www.imsdb.com/scripts/On-the-Waterfront.html",     source:"IMSDB",        draft:"Unspecified draft" },
  497: { url:"https://www.imsdb.com/scripts/Amadeus.html",               source:"IMSDB",        draft:"Unspecified draft" },
  499: { url:"https://www.imsdb.com/scripts/Platoon.html",               source:"IMSDB",        draft:"Unspecified draft" },
  500: { url:"https://www.imsdb.com/scripts/Rain-Man.html",              source:"IMSDB",        draft:"Unspecified draft" },
  502: { url:"https://www.imsdb.com/scripts/Godfather-Part-II,-The.html", source:"IMSDB",      draft:"Unspecified draft" },
  503: { url:"https://www.imsdb.com/scripts/One-Flew-Over-the-Cuckoos-Nest.html", source:"IMSDB", draft:"Unspecified draft" },
  505: { url:"https://www.imsdb.com/scripts/Midnight-Cowboy.html",       source:"IMSDB",        draft:"Unspecified draft" },
  506: { url:"https://www.dailyscript.com/scripts/french_connection.html", source:"Daily Script", draft:"Unspecified draft" },
  508: { url:"https://www.imsdb.com/scripts/Sting,-The.html",            source:"IMSDB",        draft:"Unspecified draft" },
  509: { url:"https://www.imsdb.com/scripts/Rocky.html",                 source:"IMSDB",        draft:"Unspecified draft" },
  522: { url:"https://www.imsdb.com/scripts/Braveheart.html",            source:"IMSDB",        draft:"Unspecified draft" },
  523: { url:"https://www.imsdb.com/scripts/English-Patient,-The.html",  source:"IMSDB",        draft:"Unspecified draft" },
  525: { url:"https://www.imsdb.com/scripts/Shakespeare-in-Love.html",   source:"IMSDB",        draft:"Unspecified draft" },
  526: { url:"https://www.imsdb.com/scripts/American-Beauty.html",       source:"IMSDB",        draft:"Unspecified draft" },
  527: { url:"https://www.imsdb.com/scripts/Gladiator.html",             source:"IMSDB",        draft:"Unspecified draft" },
  528: { url:"https://www.imsdb.com/scripts/Beautiful-Mind,-A.html",     source:"IMSDB",        draft:"Unspecified draft" },
  529: { url:"https://www.imsdb.com/scripts/Chicago.html",               source:"IMSDB",        draft:"Unspecified draft" },
  531: { url:"https://www.imsdb.com/scripts/Million-Dollar-Baby.html",   source:"IMSDB",        draft:"Unspecified draft" },
  533: { url:"https://www.imsdb.com/scripts/No-Country-for-Old-Men.html", source:"IMSDB",       draft:"Unspecified draft" },
  534: { url:"https://www.imsdb.com/scripts/Slumdog-Millionaire.html",   source:"IMSDB",        draft:"Unspecified draft" },
  535: { url:"https://www.imsdb.com/scripts/Hurt-Locker,-The.html",      source:"IMSDB",        draft:"Unspecified draft" },
  536: { url:"https://www.imsdb.com/scripts/King's-Speech,-The.html",    source:"IMSDB",        draft:"Unspecified draft" },
  538: { url:"https://www.imsdb.com/scripts/Argo.html",                  source:"IMSDB",        draft:"Unspecified draft" },
  539: { url:"https://www.imsdb.com/scripts/12-Years-a-Slave.html",      source:"IMSDB",        draft:"Unspecified draft" },
  540: { url:"https://www.imsdb.com/scripts/Birdman.html",               source:"IMSDB",        draft:"Unspecified draft" },
  541: { url:"https://www.imsdb.com/scripts/Spotlight.html",             source:"IMSDB",        draft:"Unspecified draft" },
  542: { url:"https://www.imsdb.com/scripts/Moonlight.html",             source:"IMSDB",        draft:"Unspecified draft" },
  543: { url:"https://www.imsdb.com/scripts/Shape-of-Water,-The.html",   source:"IMSDB",        draft:"Unspecified draft" },
  545: { url:"https://www.imsdb.com/scripts/Parasite.html",              source:"IMSDB",        draft:"Unspecified draft" },
  546: { url:"https://searchlightpictures.com/nomadland",                 source:"Searchlight",  draft:"Production draft" },
  548: { url:"https://a24films.com/films/everything-everywhere-all-at-once", source:"A24",      draft:"Production draft" },
  549: { url:"https://www.imsdb.com/scripts/Oppenheimer.html",           source:"IMSDB",        draft:"Unspecified draft" },
  552: { url:"https://www.imsdb.com/scripts/Irishman,-The.html",         source:"IMSDB",        draft:"Unspecified draft" },
  553: { url:"https://www.imsdb.com/scripts/Once-Upon-a-Time-in-Hollywood.html", source:"IMSDB", draft:"Unspecified draft" },
  554: { url:"https://www.imsdb.com/scripts/Marriage-Story.html",        source:"IMSDB",        draft:"Unspecified draft" },
  555: { url:"https://www.imsdb.com/scripts/Jojo-Rabbit.html",           source:"IMSDB",        draft:"Unspecified draft" },
  556: { url:"https://www.imsdb.com/scripts/Life-is-Beautiful.html",     source:"IMSDB",        draft:"Unspecified draft" },
  558: { url:"https://a24films.com/films/aftersun",                       source:"A24",          draft:"Production draft" },
  559: { url:"https://focusfeatures.com/tar",                             source:"Focus",        draft:"Production draft" },
  560: { url:"https://searchlightpictures.com/banshees-of-inisherin",     source:"Searchlight",  draft:"Production draft" },
  562: { url:"https://www.netflix.com/tudum/articles/all-quiet-script",   source:"Netflix",      draft:"Production draft" },
  564: { url:"https://deadline.com/2023/11/anatomy-of-a-fall-screenplay-pdf/", source:"Deadline", draft:"Final draft" },
  565: { url:"https://a24films.com/films/the-zone-of-interest",           source:"A24",          draft:"Production draft" },
  566: { url:"https://a24films.com/films/past-lives",                     source:"A24",          draft:"Production draft" },
  567: { url:"https://www.amazon.com/dp/B0CJPQ5B1F",                     source:"Amazon MGM",   draft:"Production draft" },
  570: { url:"https://a24films.com/films/the-brutalist",                  source:"A24",          draft:"Final shooting draft" },
  571: { url:"https://www.netflix.com/tudum/articles/emilia-perez-script", source:"Netflix",    draft:"Production draft" },
  572: { url:"https://neon.is/film/anora",                                source:"Neon",         draft:"Production draft" },
  577: { url:"https://mubi.com/films/the-substance",                      source:"MUBI",         draft:"Production draft" },
  587: { url:"https://a24films.com/films/showing-up",                     source:"A24",          draft:"Production draft" },
  588: { url:"https://a24films.com/films/first-cow",                      source:"A24",          draft:"Production draft" },
  590: { url:"https://a24films.com/films/certain-women",                  source:"A24",          draft:"Production draft" },
  593: { url:"https://neon.is/film/portrait-of-a-lady-on-fire",           source:"Neon",         draft:"Production draft" },
  594: { url:"https://criterion.com/films/petite-maman",                  source:"Criterion",    draft:"Production draft" },
  598: { url:"https://neon.is/film/the-worst-person-in-the-world",        source:"Neon",         draft:"Production draft" },
};
