// ─────────────────────────────────────────────────────────────────────────────
// TOP 100 VINTAGE PIECES
// ─────────────────────────────────────────────────────────────────────────────
export const VINTAGE = [
  // ── HOLY GRAIL ────────────────────────────────────────────────────────────
  { id:1,  rank:1,  name:"Levi's Type I Cinch-Back Denim Jacket", brand:"Levi Strauss & Co.", era:"1930s", category:"Denim", rarity:"holy grail", value:"$10,000–$50,000", findable:false, description:"The original, pre-WWII denim jacket with a cinch strap at the back and pleated chest — made before fabric rationing changed everything. Levi's first true trucker jacket. A sealed, unworn example sold at auction for over $50,000. The rarest piece of American workwear." },
  { id:2,  rank:2,  name:"Levi's 501XX Big E Double Stitched (1940s–50s)", brand:"Levi Strauss & Co.", era:"1940s–50s", category:"Denim", rarity:"holy grail", value:"$5,000–$30,000", findable:false, description:"The original 501XX with the capital-E 'Big E' red tab, hidden rivets, and suspender buttons. Pre-1971 manufacture. A deadstock pair in any size commands five figures. The foundational garment of American style." },
  { id:3,  rank:3,  name:"WWII US Army M-1941 Field Jacket", brand:"US Military Issue", era:"1940s", category:"Military", rarity:"holy grail", value:"$3,000–$15,000", findable:false, description:"The field jacket that inspired every military jacket since. Made from HBT (herringbone twill) cotton, with a distinctive four-pocket silhouette. Named individuals and unit markings make each one a document of history." },
  { id:4,  rank:4,  name:"Wrangler 11MWZ Cowboy Cut Deadstock (1940s)", brand:"Wrangler", era:"1940s", category:"Denim", rarity:"holy grail", value:"$3,000–$12,000", findable:false, description:"The original rodeo jean designed by rodeo champion Buddy Rodgers in 1947. Deadstock 40s examples have the original rivet construction and W stitching. The jeans that won the West." },
  { id:5,  rank:5,  name:"Lee 101B Denim Jacket (1950s, One-Wash)", brand:"H.D. Lee Co.", era:"1950s", category:"Denim", rarity:"holy grail", value:"$2,000–$10,000", findable:false, description:"Lee's answer to Levi's trucker, with the distinctive storm rider collar and blanket-lined winter version. The 1950s one-wash examples with original hardware are extraordinarily rare." },
  { id:6,  rank:6,  name:"Perfecto 618 Horsehide Motorcycle Jacket (1950s)", brand:"Schott NYC", era:"1950s", category:"Leather", rarity:"holy grail", value:"$5,000–$20,000", findable:false, description:"Marlon Brando wore it in The Wild One and every rebel since has chased the original. The Perfecto 618 in horsehide — made before cowhide became standard — is the definitive biker jacket. An original 1950s example is among the most sought pieces of American clothing." },
  { id:7,  rank:7,  name:"Champion Reverse Weave Sweatshirt (1940s–50s)", brand:"Champion Products", era:"1940s–50s", category:"Sportswear", rarity:"holy grail", value:"$1,000–$5,000", findable:false, description:"The original Reverse Weave with the faded script 'Champion' and the horizontal weave that prevents shrinkage lengthwise. Early examples with chain-stitched text are extraordinarily rare. The foundation of American sportswear." },
  { id:8,  rank:8,  name:"USN N-1 Deck Jacket (WWII)", brand:"US Navy Issue", era:"1940s", category:"Military", rarity:"holy grail", value:"$2,000–$8,000", findable:false, description:"The alpaca-lined navy deck jacket worn on aircraft carriers in the Pacific. Its distinctive silhouette — short body, stand collar, knit cuffs — influenced a century of outerwear. Original examples with USN stenciling are holy grail military surplus." },
  { id:9,  rank:9,  name:"Levi's Type II Denim Jacket Big E (1950s–60s)", brand:"Levi Strauss & Co.", era:"1950s–60s", category:"Denim", rarity:"very rare", value:"$1,000–$6,000", findable:false, description:"The two-pocket design that succeeded the Type I. The Big E version (pre-1971) with original hardware, cinch back, and orange tab on breast pocket is the defining denim jacket of the 50s and 60s. Worn by everyone from James Dean to Bob Dylan." },
  { id:10, rank:10, name:"USAAF A-2 Flight Jacket (WWII, Named)", brand:"Various Contract Makers", era:"1940s", category:"Military / Leather", rarity:"holy grail", value:"$3,000–$15,000", findable:false, description:"The horsehide flight jacket issued to US Army Air Forces pilots during WWII. Named examples with hand-painted nose art on the back are among the most collectible American garments ever made. Each one is a unique artifact of a specific person and mission." },

  // ── VERY RARE ─────────────────────────────────────────────────────────────
  { id:11, rank:11, name:"Levi's 501 Red Line Selvedge (1960s, Deadstock)", brand:"Levi Strauss & Co.", era:"1960s", category:"Denim", rarity:"very rare", value:"$800–$4,000", findable:false, description:"The red-line selvedge denim, woven on shuttle looms at Cone Mills, North Carolina. Made before Levi's switched to open-end spinning in 1982. A deadstock pair with the original 55 cut is increasingly unobtainable." },
  { id:12, rank:12, name:"Buzz Rickson MA-1 Flight Jacket (Original 1960s)", brand:"Various Contract Makers", era:"1960s", category:"Military", rarity:"very rare", value:"$500–$3,000", findable:true, description:"The nylon bomber that replaced the A-2 in the jet age. Original 60s examples in the USAF sage green with the blood chit have become extraordinarily collectible. Buzz Rickson's modern reproductions are the benchmark, but an original is another level." },
  { id:13, rank:13, name:"Pendleton 49er Jacket (1950s–60s)", brand:"Pendleton Woolen Mills", era:"1950s–60s", category:"Outerwear", rarity:"very rare", value:"$300–$1,500", findable:true, description:"The wool shirt-jacket from Oregon that defined the early surf and collegiate look. The 49er jacket in original 50s–60s wool — bright plaid, warm construction — is a cornerstone of American heritage dressing." },
  { id:14, rank:14, name:"Levi's 506XX Denim Jacket (1930s–40s)", brand:"Levi Strauss & Co.", era:"1930s–40s", category:"Denim", rarity:"holy grail", value:"$3,000–$20,000", findable:false, description:"The second iteration after the Type I, with a pleated breast but no cinch back. Made during WWII rationing, these pieces are extraordinarily rare. The most historically significant denim jacket between the Type I and Type II." },
  { id:15, rank:15, name:"Walt Disney Studios Animator's Jacket (1940s)", brand:"Various", era:"1940s", category:"Workwear / Specialty", rarity:"holy grail", value:"$5,000–$25,000", findable:false, description:"Studio-issued jackets given to Disney animators working on films like Fantasia and Dumbo. Chain-stitched with film titles or character art. Among the rarest examples of American pop-culture workwear." },
  { id:16, rank:16, name:"Converse Chuck Taylor All Star (1960s, Deadstock)", brand:"Converse", era:"1960s", category:"Footwear", rarity:"very rare", value:"$500–$3,000", findable:false, description:"The original canvas hi-top in deadstock 1960s condition, with the correct ankle patch, black foxing, and made-in-USA construction. The shoe that defined American basketball and then defined American cool." },
  { id:17, rank:17, name:"Levis 646 Bell Bottom Flares (1970s, Deadstock)", brand:"Levi Strauss & Co.", era:"1970s", category:"Denim", rarity:"very rare", value:"$400–$2,000", findable:true, description:"The extreme flare silhouette of the early 70s. Deadstock 646s in orange selvedge denim are increasingly rare. An era-defining silhouette that cycling fashion has made relevant again." },
  { id:18, rank:18, name:"Schott Perfecto 618 Cowhide (1960s–70s)", brand:"Schott NYC", era:"1960s–70s", category:"Leather", rarity:"very rare", value:"$800–$3,000", findable:true, description:"The cowhide iteration of the legendary Perfecto. The transition from horsehide to cowhide happened in the 1960s. Original 60s–70s examples with the belted waist, asymmetric zip and epaulets remain the definitive biker jacket form." },
  { id:19, rank:19, name:"Carhartt Detroit Jacket (1980s, Chore Coat)", brand:"Carhartt", era:"1980s", category:"Workwear", rarity:"rare", value:"$150–$600", findable:true, description:"The blanket-lined Detroit jacket from before Carhartt became fashion. Original 80s examples with the correct triple-stitched seams, hammered-copper rivets and Carhartt label in duck canvas are the platonic ideal of American workwear." },
  { id:20, rank:20, name:"Levi's Sherpa Trucker Jacket Type III (1970s)", brand:"Levi Strauss & Co.", era:"1970s", category:"Denim", rarity:"very rare", value:"$400–$2,000", findable:true, description:"The Type III denim jacket with the original sherpa lining. The 70s examples with the small-e tab and original lining have become one of the most sought vintage denim pieces. The sherpa trucker defined an era." },

  // ── RARE ──────────────────────────────────────────────────────────────────
  { id:21, rank:21, name:"Polo Ralph Lauren 'Snow Beach' Pullover (1993)", brand:"Polo Ralph Lauren", era:"1990s", category:"Sportswear", rarity:"very rare", value:"$1,000–$5,000", findable:false, description:"The ski-inspired pullover from the 1993 Snow Beach collection, worn by Raekwon on the Only Built 4 Cuban Linx cover. Hip-hop's most iconic Ralph Lauren piece. An original is among the rarest 90s sportswear grails." },
  { id:22, rank:22, name:"Champion 'Reverse Weave' Hoodie with Tags (1980s)", brand:"Champion Products", era:"1980s", category:"Sportswear", rarity:"very rare", value:"$300–$1,200", findable:true, description:"Before hypebeast culture, Champion was authentic American sportswear. An 80s Reverse Weave hoodie with original tags, the block-letter logo, and the horizontal rib construction is the original. Everything since is a copy." },
  { id:23, rank:23, name:"Levi's 501 STF (Shrink-to-Fit) Raw 1980s", brand:"Levi Strauss & Co.", era:"1980s", category:"Denim", rarity:"rare", value:"$200–$800", findable:true, description:"The last era of the original 501 construction before mass-production shortcuts. Shrink-to-fit raw denim that forms to the body. The 80s examples are the last of a genuine American tradition." },
  { id:24, rank:24, name:"Harley-Davidson Dealer Tee (1970s)", brand:"Harley-Davidson", era:"1970s", category:"T-Shirts", rarity:"very rare", value:"$300–$1,500", findable:true, description:"Original dealership tees from the 1970s with faded screen print graphics and single-stitch construction. The bar-and-shield logo on tissue-thin cotton is the gold standard of American graphic tees." },
  { id:25, rank:25, name:"Stone Island Nylon Metal Jacket (1989)", brand:"Stone Island", era:"1980s", category:"Outerwear", rarity:"very rare", value:"$2,000–$8,000", findable:false, description:"The original Nylon Metal — a fabric treated with a metallic coating that gives it an iridescent sheen. Massimo Osti's masterpiece from the label's early years. The defining Stone Island piece before the brand became global." },
  { id:26, rank:26, name:"Stüssy Vintage Crown Logo Hoodie (Early 1990s)", brand:"Stüssy", era:"1990s", category:"Streetwear", rarity:"very rare", value:"$400–$2,000", findable:true, description:"Early 90s Stüssy with Shawn Stussy's signature crown logo and the heavyweight cotton construction. Before the brand went global. Worn by the founders of streetwear culture in Laguna Beach and NYC." },
  { id:27, rank:27, name:"Polo Ralph Lauren 'Stadium' Jacket (1992)", brand:"Polo Ralph Lauren", era:"1990s", category:"Sportswear", rarity:"very rare", value:"$800–$4,000", findable:false, description:"The 1992 Stadium pullover — the pinnacle of Lo Life culture. Color-blocked, logo-heavy, worn by the Brooklyn crew who built Polo's street credibility. Original examples with tags are extremely scarce." },
  { id:28, rank:28, name:"Levi's Orange Tab Bell Bottom (1970s)", brand:"Levi Strauss & Co.", era:"1970s", category:"Denim", rarity:"rare", value:"$200–$800", findable:true, description:"The orange-tab flare jeans of the 70s in selvedge denim — the everyday counterpart to the more collectible red-tab 501. An era-defining silhouette that appears every decade." },
  { id:29, rank:29, name:"G.H. Bass Weejun Penny Loafer (1960s)", brand:"G.H. Bass & Company", era:"1960s", category:"Footwear", rarity:"rare", value:"$200–$800", findable:true, description:"The penny loafer that defined Ivy League preppy style. Made in Maine in the 1960s with full-grain leather and a genuine moccasin sole. An original with the correct construction is far superior to any modern reissue." },
  { id:30, rank:30, name:"Red Wing 2268 Iron Ranger Boot (Pre-1980)", brand:"Red Wing Shoes", era:"1950s–70s", category:"Footwear", rarity:"rare", value:"$400–$1,500", findable:true, description:"The original Iron Ranger in Amber Harness leather, made in Red Wing, MN. Pre-1980 examples with the correct cap toe, Vibram sole, and full-grain leather command significant premiums. The definitive American work boot." },

  // ── FINDABLE ──────────────────────────────────────────────────────────────
  { id:31, rank:31, name:"Levi's 505 Straight Leg (1970s–80s)", brand:"Levi Strauss & Co.", era:"1970s–80s", category:"Denim", rarity:"findable", value:"$80–$300", findable:true, description:"The straight-leg alternative to the 501. 70s–80s examples in selvedge denim are still findable in good vintage shops. The 505 was the working man's jean — less precious, more worn." },
  { id:32, rank:32, name:"Nike Windrunner Jacket (1980s)", brand:"Nike", era:"1980s", category:"Sportswear", rarity:"rare", value:"$150–$600", findable:true, description:"The original Windrunner in the chevron colorblock design. 80s examples with the correct nylon construction and embroidered swoosh are the holy grail of Nike vintage. One of the most recognizable sportswear silhouettes ever made." },
  { id:33, rank:33, name:"Adidas Trefoil Track Top (1970s–80s)", brand:"Adidas", era:"1970s–80s", category:"Sportswear", rarity:"rare", value:"$150–$600", findable:true, description:"The original three-stripe track jacket with the trefoil logo, made in West Germany. Run-DMC made it iconic. Original 70s–80s examples in the correct nylon with the three stripes running the full length are increasingly hard to find." },
  { id:34, rank:34, name:"Patagonia Pile Fleece (1980s, Snap-T)", brand:"Patagonia", era:"1980s", category:"Outerwear", rarity:"rare", value:"$200–$800", findable:true, description:"The original Synchilla Snap-T in the 80s colorways — teal, purple, and coral. Yvon Chouinard's fleece revolution. Original 80s examples with the correct label and unbonded construction are highly collectible." },
  { id:35, rank:35, name:"Barbour Beaufort Wax Jacket (1980s, UK Made)", brand:"Barbour", era:"1980s", category:"Outerwear", rarity:"rare", value:"$200–$700", findable:true, description:"Made in South Shields, England, with genuine waxed cotton and a corduroy collar. 80s examples with the correct tartan lining and the South Shields label are significantly superior to modern production." },
  { id:36, rank:36, name:"Levi's 550 Relaxed Fit (1990s, Deadstock)", brand:"Levi Strauss & Co.", era:"1990s", category:"Denim", rarity:"findable", value:"$60–$200", findable:true, description:"The relaxed fit that defined 90s denim culture. Deadstock 90s 550s in the correct stone-wash are findable but increasingly picked over. The quintessential 90s jean." },
  { id:37, rank:37, name:"Carhartt Active Jacket (1990s, Quilted Flannel Lined)", brand:"Carhartt", era:"1990s", category:"Workwear", rarity:"findable", value:"$60–$200", findable:true, description:"The quilted-flannel-lined Active Jacket in duck canvas or sandstone. 90s examples with the original brass hardware and triple-stitched seams are workwear royalty. Still findable — for now." },
  { id:38, rank:38, name:"Ralph Lauren Polo Oxford Shirt (1980s, RLPL)", brand:"Ralph Lauren", era:"1980s", category:"Shirts", rarity:"findable", value:"$50–$200", findable:true, description:"The Oxford shirt that defined American preppy — button-down collar, Polo player embroidery, made of genuine Oxford cloth. 80s examples in original condition are significantly better quality than anything made today." },
  { id:39, rank:39, name:"Tommy Hilfiger Colorblock Jacket (1990s)", brand:"Tommy Hilfiger", era:"1990s", category:"Sportswear", rarity:"findable", value:"$80–$300", findable:true, description:"The red, white, and blue colorblock windbreaker that defined 90s hip-hop fashion. Tommy's brand was built on these jackets — worn by Snoop, Puffy, and a generation of New Yorkers." },
  { id:40, rank:40, name:"Levi's 501 'Made in USA' (1980s–90s)", brand:"Levi Strauss & Co.", era:"1980s–90s", category:"Denim", rarity:"findable", value:"$60–$200", findable:true, description:"The last era of US-manufactured 501s before production moved offshore. The 'Made in USA' label commands a premium. These are the last true American Levi's, and they're still findable in every thrift store in the country." },
  { id:41, rank:41, name:"Polo Ralph Lauren Cable Knit Crewneck (1980s–90s)", brand:"Ralph Lauren", era:"1980s–90s", category:"Knitwear", rarity:"findable", value:"$80–$300", findable:true, description:"The cable-knit sweater that defined East Coast preppy. 80s–90s examples in lambswool or merino with the Polo player embroidery are the real deal. Cotton versions are common; wool versions are the prize." },
  { id:42, rank:42, name:"Lee Riders 101Z (1950s–60s)", brand:"H.D. Lee Co.", era:"1950s–60s", category:"Denim", rarity:"very rare", value:"$400–$2,000", findable:false, description:"Lee's definitive straight-leg jean, the 101Z with the back cinch strap. Worn by Elvis Presley and James Dean. Original 50s–60s examples with Lee's distinctive Union-All label are among the most collectible non-Levi's denim." },
  { id:43, rank:43, name:"Dickies 874 Work Pants (1970s–80s, USA Made)", brand:"Dickies", era:"1970s–80s", category:"Workwear", rarity:"findable", value:"$40–$150", findable:true, description:"Made in the USA before offshore production — the original 874 in twill with the correct high rise and straight leg. Adopted by skaters, punks, and hip-hop heads in the 90s. Still findable in abundance." },
  { id:44, rank:44, name:"Filson Tin Cloth Packer Coat (1970s–80s)", brand:"Filson", era:"1970s–80s", category:"Outerwear", rarity:"rare", value:"$300–$1,000", findable:true, description:"Made in Seattle since 1897. Original Filson tin cloth in early examples is noticeably heavier and better constructed than current production. The definitive Pacific Northwest outdoor garment." },
  { id:45, rank:45, name:"Ray-Ban Wayfarer (Original 1950s–60s)", brand:"Bausch & Lomb / Ray-Ban", era:"1950s–60s", category:"Accessories", rarity:"rare", value:"$200–$800", findable:true, description:"The original Wayfarer in Bakelite — before Ray-Ban switched to acetate. Made by Bausch & Lomb in the USA, these have a different, heavier feel. Worn by James Dean, Bob Dylan, and every generation of cool since." },
  { id:46, rank:46, name:"Comme des Garçons Homme Plus (1980s, Archive)", brand:"Comme des Garçons", era:"1980s", category:"Designer / Avant-Garde", rarity:"holy grail", value:"$1,000–$10,000", findable:false, description:"Rei Kawakubo's early 80s collections that introduced 'poverty chic' to the Paris runway. Torn hems, asymmetric silhouettes, all-black. Shocked and offended Paris. Changed fashion forever. Original pieces are museum-level." },
  { id:47, rank:47, name:"Yohji Yamamoto Pour Homme (1980s, Archive)", brand:"Yohji Yamamoto", era:"1980s", category:"Designer / Avant-Garde", rarity:"holy grail", value:"$1,000–$8,000", findable:false, description:"Yohji's early 80s collections alongside Kawakubo reshaped Western fashion. Oversized, deconstructed, deeply Japanese in philosophy. Original 80s Yohji pieces with the correct label are priceless documents of avant-garde fashion." },
  { id:48, rank:48, name:"Helmut Lang Archive Jeans (1990s–early 2000s)", brand:"Helmut Lang", era:"1990s–2000s", category:"Designer", rarity:"very rare", value:"$300–$2,000", findable:false, description:"Pre-Prada acquisition Helmut Lang is the definitive minimalist designer archive. The raw selvedge denim jeans from his 1998–2003 collections are among the most influential pants in fashion history. Everything from Raf to Hedi can trace a line back here." },
  { id:49, rank:49, name:"Raf Simons SS02 'Riot Riot Riot' Jacket", brand:"Raf Simons", era:"2000s", category:"Designer", rarity:"holy grail", value:"$5,000–$30,000", findable:false, description:"From the Spring/Summer 2002 collection that defined post-millennial youth culture. Slim-cut jackets with slogans, punk references, and confrontational graphics. Among the most studied and copied collections in designer history." },
  { id:50, rank:50, name:"Levi's 517 Boot Cut (1970s, Orange Tab)", brand:"Levi Strauss & Co.", era:"1970s", category:"Denim", rarity:"findable", value:"$80–$300", findable:true, description:"The boot-cut counterpart to the 501, popular in the 70s country and western revival. Original examples in orange-tab selvedge are still findable and represent one of the best proportions Levi's ever produced." },
  { id:51, rank:51, name:"Vans Sk8-Hi (Original 1970s, Made in USA)", brand:"Vans", era:"1970s", category:"Footwear", rarity:"very rare", value:"$500–$2,000", findable:false, description:"Made in the Anaheim factory in the 1970s, with the correct waffle sole and canvas upper. Van Doren Rubber Company originals predate the brand's mainstream popularity. A skateboarding grail." },
  { id:52, rank:52, name:"New Balance 990 (Made in USA, 1982 Original)", brand:"New Balance", era:"1980s", category:"Footwear", rarity:"very rare", value:"$400–$2,000", findable:false, description:"The original $100 running shoe — the first to cost that much — made in Massachusetts. Original 1982 examples with the correct pigskin suede and N logo are among the rarest American sneaker collectibles." },
  { id:53, rank:53, name:"Nike Air Max 1 (1987, Original Colorway)", brand:"Nike", era:"1980s", category:"Footwear", rarity:"very rare", value:"$500–$3,000", findable:false, description:"Tinker Hatfield's radical idea: put the air unit on display. The original 1987 Air Max 1 in Sport Red/White/Sport Blue is the ancestor of every visible-air sneaker since. Original examples are near-impossible to find unworn." },
  { id:54, rank:54, name:"Air Jordan 1 'Bred' (1985, Original)", brand:"Nike / Jordan Brand", era:"1980s", category:"Footwear", rarity:"holy grail", value:"$5,000–$30,000", findable:false, description:"The shoe that NBA banned and Nike paid the fine for. Michael Jordan wore it and changed sneaker culture forever. Original 1985 pairs in any condition are worth five figures. The most important shoe in American history." },
  { id:55, rank:55, name:"Supreme Box Logo Hoodie (2000s, Early)", brand:"Supreme", era:"2000s", category:"Streetwear", rarity:"very rare", value:"$500–$3,000", findable:false, description:"James Jebbia's downtown NYC skate brand's signature piece from the early 2000s before the hype explosion. Early box logo hoodies with the correct heavyweight construction and boxy fit are the originals. Everything after 2012 is a different thing." },
  { id:56, rank:56, name:"WTAPS Buds Jacket (2000s, Archive)", brand:"WTAPS", era:"2000s", category:"Streetwear / Military", rarity:"very rare", value:"$500–$2,500", findable:false, description:"Tetsu Nishiyama's military-inspired Japanese streetwear brand. The Buds jacket — inspired by US military BDU design — is the definitive WTAPS piece. Early 2000s examples are the most collectible." },
  { id:57, rank:57, name:"Neighborhood NHIX Biker Jacket (Late 1990s)", brand:"Neighborhood", era:"1990s", category:"Leather / Streetwear", rarity:"very rare", value:"$800–$3,000", findable:false, description:"Shinsuke Takizawa's Harajuku brand merged biker culture with Japanese craftsmanship. Late 90s horsehide examples from before the brand scaled are the most coveted. The original Japanese street leather." },
  { id:58, rank:58, name:"Carhartt WIP Logo Hoodie (Early 2000s, Europe)", brand:"Carhartt WIP", era:"2000s", category:"Streetwear / Workwear", rarity:"findable", value:"$80–$300", findable:true, description:"The European street-skate reinterpretation of American workwear. Early 2000s Carhartt WIP pieces with the correct canvas and the original WIP branding are now vintage in their own right." },
  { id:59, rank:59, name:"A.P.C. New Standard Jeans (1987, First Run)", brand:"A.P.C.", era:"1980s–90s", category:"Denim", rarity:"rare", value:"$200–$800", findable:false, description:"Jean Touitou's raw Japanese selvedge denim jeans from 1987 — the first European fashion brand to make raw denim accessible. Original first-run examples are extremely rare. Inspired a generation of raw denim obsessives." },
  { id:60, rank:60, name:"Levi's 646 Super Bell Bottom (1970s, Deadstock)", brand:"Levi Strauss & Co.", era:"1970s", category:"Denim", rarity:"very rare", value:"$400–$2,000", findable:false, description:"The extreme 30-inch hem circumference bell bottom. The most exaggerated denim silhouette Levi's ever produced. Deadstock 70s examples are extraordinarily hard to find in any wearable size." },
  { id:61, rank:61, name:"Wrangler 13MWZ Cowboy Cut (1950s–60s)", brand:"Wrangler", era:"1950s–60s", category:"Denim", rarity:"rare", value:"$300–$1,200", findable:false, description:"The definitive rodeo jean with the W-stitch and the high rise. Worn by every PBR champion. 50s–60s examples with the original construction are increasingly rare as the vintage denim market matures." },
  { id:62, rank:62, name:"Barbour International Jacket (1970s, UK Made)", brand:"Barbour", era:"1970s", category:"Outerwear", rarity:"rare", value:"$300–$1,000", findable:true, description:"Designed for the Isle of Man TT motorcycle race. The original International with the correct waxed cotton and tartan lining is the supreme motorcycle jacket from Britain. Worn by Steve McQueen." },
  { id:63, rank:63, name:"Brooks Brothers OCBD Shirt (1960s, USA Made)", brand:"Brooks Brothers", era:"1960s", category:"Shirts", rarity:"rare", value:"$100–$400", findable:true, description:"The Oxford Cloth Button Down that invented Ivy League style in the 1950s–60s. Original US-made examples in Egyptian cotton are significantly better than modern production. The reference point for every OCBD made since." },
  { id:64, rank:64, name:"Levi's 70506 Type III Denim Jacket (1970s, Small-E)", brand:"Levi Strauss & Co.", era:"1970s", category:"Denim", rarity:"rare", value:"$200–$800", findable:true, description:"The small-e tab Type III trucker from the 70s. The most wearable vintage Levi's jacket — the Big E is rarer, but the 70s small-e is the sweet spot of quality and findability." },
  { id:65, rank:65, name:"Levis 501 'Redline' Selvedge 1960s", brand:"Levi Strauss & Co.", era:"1960s", category:"Denim", rarity:"very rare", value:"$600–$3,000", findable:false, description:"The red-line selvedge woven at Cone Mills. Identifiable by the faint red line running along the outseam. Made before Levi's abandoned selvedge looms in the 1980s. A cornerstone of Japanese denim culture's obsession with American originals." },
  { id:66, rank:66, name:"Polo Ralph Lauren 'Polo Bear' Sweater (1990s)", brand:"Ralph Lauren", era:"1990s", category:"Knitwear", rarity:"rare", value:"$200–$800", findable:true, description:"The intarsia knit sweater featuring the polo-playing bear in various seasonal outfits. A beloved 90s Ralph Lauren piece that has become one of the most recognizable vintage knitwear items." },
  { id:67, rank:67, name:"Stone Island Shadow Project AW2010", brand:"Stone Island", era:"2010s", category:"Outerwear / Designer", rarity:"very rare", value:"$800–$4,000", findable:false, description:"The Shadow Project diffusion line designed in collaboration with Errolson Hugh of ACRONYM. Technical outerwear at its most extreme. Early Shadow Project pieces are the intersection of hi-tech functionality and fashion collectibility." },
  { id:68, rank:68, name:"Issey Miyake Pleats Please (1990s, Original)", brand:"Issey Miyake", era:"1990s", category:"Designer", rarity:"rare", value:"$200–$800", findable:true, description:"The polyester pleated garments that are functional design classics. Original 90s Pleats Please pieces in the correct colors are fashion history. Steve Jobs's black turtleneck was a Miyake original." },
  { id:69, rank:69, name:"Vintage Hawaiian Shirt 'Aloha' (1940s–50s, Silk)", brand:"Various (Kamehameha, Shaheen)", era:"1940s–50s", category:"Shirts", rarity:"very rare", value:"$500–$3,000", findable:false, description:"Original Hawaiian aloha shirts in rayon or silk from the post-WWII era. Look for Kamehameha, Shaheen, and Kahala labels. The design tradition of Polynesian patterns on lightweight fabric is one of the most joyful in American clothing history." },
  { id:70, rank:70, name:"Levi's Red Tab Corduroy Jacket (1970s)", brand:"Levi Strauss & Co.", era:"1970s", category:"Other", rarity:"rare", value:"$200–$700", findable:true, description:"Levi's applied their trucker jacket silhouette to corduroy in the 70s. These wide-wale pieces in earthy 70s tones — rust, mustard, brown — represent the decade's aesthetic perfectly." },
  { id:71, rank:71, name:"Band T-Shirt (Rolling Stones 1972 Tour, Original)", brand:"Various / Tour Merch", era:"1970s", category:"T-Shirts", rarity:"holy grail", value:"$2,000–$10,000", findable:false, description:"Original concert tees from the 1972 Exile on Main St. tour. Single-stitch construction, Screen Stars or Hanes blank, faded graphics. Vintage band tees from 1970s tours are among the most rapidly appreciating vintage categories." },
  { id:72, rank:72, name:"Metallica 'Damage Inc.' Tour Tee (1986–87)", brand:"Tour Merch", era:"1980s", category:"T-Shirts", rarity:"very rare", value:"$500–$3,000", findable:false, description:"The original Damage Inc. tour tee from the Master of Puppets cycle. Original 80s metal concert tees in wearable condition have become extremely collectible. Single stitch, faded print, tissue-thin cotton." },
  { id:73, rank:73, name:"Nirvana 'Nevermind' Tour Tee (1991–92)", brand:"Tour Merch", era:"1990s", category:"T-Shirts", rarity:"very rare", value:"$500–$2,000", findable:false, description:"The original Nevermind-era tour tee, single-stitch, with original Brockum or Giant tag. Nirvana vintage tees have exploded in value as grunge nostalgia peaks. Original 91–92 examples are increasingly hard to verify." },
  { id:74, rank:74, name:"Lee 101-J Storm Rider Jacket (1950s–60s)", brand:"H.D. Lee Co.", era:"1950s–60s", category:"Denim", rarity:"very rare", value:"$600–$3,000", findable:false, description:"The iconic blanket-lined Storm Rider with the distinctive corduroy collar. The cowboy alternative to Levi's trucker. Original 50s–60s examples with the original lining are extraordinarily rare." },
  { id:75, rank:75, name:"Comme des Garçons Play Heart Tee (2000s, Early)", brand:"Comme des Garçons PLAY", era:"2000s", category:"T-Shirts", rarity:"findable", value:"$60–$200", findable:true, description:"The heart-with-eyes logo on a plain tee. Early 2000s examples are made in Japan with slightly different construction. The most accessible entry point into the CDG universe — and one that only grows in cultural relevance." },
  { id:76, rank:76, name:"Filson Mackinaw Wool Cruiser (1960s–70s)", brand:"Filson", era:"1960s–70s", category:"Outerwear", rarity:"rare", value:"$300–$1,000", findable:true, description:"The heavyweight Mackinaw wool coat made in Seattle for Pacific Northwest loggers. Original 60s–70s examples in the correct virgin wool are among the finest American outdoor garments ever made." },
  { id:77, rank:77, name:"Patagonia Baggies Shorts (1980s, Original)", brand:"Patagonia", era:"1980s", category:"Sportswear", rarity:"rare", value:"$100–$400", findable:true, description:"The original nylon Baggies from the early 80s in the correct vintage colorways — ocean, mango, and kelp. Yvon Chouinard's first major product hit. The 80s examples predate the environmental mission but embody it perfectly." },
  { id:78, rank:78, name:"Levi's 512 Slim Tapered (1980s, USA Made)", brand:"Levi Strauss & Co.", era:"1980s", category:"Denim", rarity:"findable", value:"$60–$200", findable:true, description:"The slim tapered fit from the 80s that anticipated modern silhouettes by 30 years. Still made in USA, the 80s examples have the correct higher rise and taper. The best proportioned Levi's for modern wear." },
  { id:79, rank:79, name:"Woolrich Arctic Parka (1970s–80s)", brand:"Woolrich", era:"1970s–80s", category:"Outerwear", rarity:"rare", value:"$200–$700", findable:true, description:"Made in Pennsylvania since 1830, Woolrich's Arctic Parka is the American answer to the N-3B. 70s–80s examples in the correct virgin wool or down fill with the coyote fur-ruff hood are superior to any modern version." },
  { id:80, rank:80, name:"Engineered Garments Bedford Jacket (Early 2000s)", brand:"Engineered Garments", era:"2000s", category:"Outerwear", rarity:"rare", value:"$200–$600", findable:true, description:"Daiki Suzuki's New York take on American workwear and military clothing. Early EG Bedford jackets in original fabrics are now genuinely vintage. The brand that made Americana wearable for a new generation." },
  { id:81, rank:81, name:"BAPE 1st Camo Hoodie (Early 2000s)", brand:"A Bathing Ape", era:"2000s", category:"Streetwear", rarity:"very rare", value:"$500–$2,500", findable:false, description:"NIGO's ape camo in the original 2001–2005 production run, before the brand was sold. The zip-up hoodie in the first camo print is the foundational piece of Japanese streetwear. Everything about BAPE's cultural moment is contained in this garment." },
  { id:82, rank:82, name:"Acne Studios Max Cash Jeans (2005, Original)", brand:"Acne Studios", era:"2000s", category:"Denim", rarity:"rare", value:"$200–$700", findable:false, description:"The raw denim jeans that launched Acne Studios — Jonny Johansson made 100 pairs and gave them to friends. The genesis of Scandinavian minimalism in denim. Original Max Cash jeans are design history." },
  { id:83, rank:83, name:"Pendleton Wool Board Shirt (1960s)", brand:"Pendleton Woolen Mills", era:"1960s", category:"Shirts", rarity:"findable", value:"$80–$300", findable:true, description:"The heavy wool board shirt from the 60s in original tartan plaids. Pendleton's shirts were adopted by the Grateful Dead's audience, early skaters, and grunge musicians. An original 60s board shirt in wool is an evergreen piece." },
  { id:84, rank:84, name:"Levi's SilverTab Baggy (1990s)", brand:"Levi Strauss & Co.", era:"1990s", category:"Denim", rarity:"findable", value:"$60–$200", findable:true, description:"The silver-tab baggy jean that defined 90s skate and hip-hop denim. Deadstock 90s examples are findable in thrift stores but the market has noticed. The 90s alternative to the 501." },
  { id:85, rank:85, name:"Reebok Classic Leather (1983, USA Made)", brand:"Reebok", era:"1980s", category:"Footwear", rarity:"rare", value:"$200–$800", findable:false, description:"The aerobics shoe that became a streetwear staple. Original 1983 US-made examples in full-grain leather with the vector logo are the rarest Reebok. The garment district of Boston made these." },
  { id:86, rank:86, name:"Walt Disney World Souvenir Tee (1970s)", brand:"Various / Disney", era:"1970s", category:"T-Shirts", rarity:"rare", value:"$150–$600", findable:true, description:"Original Disney World souvenir tees from the 1970s — single stitch, screen-printed character graphics on tissue-thin cotton. Mickey Mouse in 70s palette is the most graphic representation of American pop culture." },
  { id:87, rank:87, name:"Champion Mesh Practice Jersey (1970s–80s)", brand:"Champion Products", era:"1970s–80s", category:"Sportswear", rarity:"rare", value:"$100–$400", findable:true, description:"Original mesh practice jerseys with university and team names, made by Champion for college athletics. The originals have a different hand than modern replicas — lighter mesh, single stitch. A cornerstone of American sportswear history." },
  { id:88, rank:88, name:"Denim Chore Coat (1930s–40s, Indigo)", brand:"Various (Big Mac, Key, Boss of the Road)", era:"1930s–40s", category:"Workwear / Denim", rarity:"very rare", value:"$500–$3,000", findable:false, description:"The pre-war chore coat in indigo-dyed denim, worn by American farmers and laborers. Various makers — Big Mac, Key, Boss of the Road — produced these in the 30s–40s. An example with original hardware and intact label is a workwear holy grail." },
  { id:89, rank:89, name:"Red Kap Work Shirt (1970s–80s)", brand:"Red Kap", era:"1970s–80s", category:"Workwear", rarity:"findable", value:"$40–$150", findable:true, description:"The original service-industry work shirt in poplin with embroidered name patches. Gas station attendants, mechanics, and diner workers wore these. The most honest American garment — functional, durable, zero pretension." },
  { id:90, rank:90, name:"Levi's 503B Big E Slim (1960s)", brand:"Levi Strauss & Co.", era:"1960s", category:"Denim", rarity:"very rare", value:"$400–$2,000", findable:false, description:"The slim-fit counterpart to the 501 from the Big E era. Less common than the 501, the 503B has a slightly narrower cut that reads as modern. Original Big E examples are extremely rare." },
  { id:91, rank:91, name:"Nike Dunk Low (1985, OG University Colorways)", brand:"Nike", era:"1980s", category:"Footwear", rarity:"very rare", value:"$800–$4,000", findable:false, description:"The original 1985 college pack — made to match university colors for basketball teams. Original 85 Dunks in any of the original seven colorways are among the rarest American sneakers. The OG of skate footwear." },
  { id:92, rank:92, name:"Coach Leather Bag (1970s–80s, Bonnie Cashin Era)", brand:"Coach", era:"1970s–80s", category:"Accessories", rarity:"rare", value:"$200–$800", findable:true, description:"Coach before the brand became mall-ubiquitous. Bonnie Cashin's original designs in full-grain steerhide leather are indestructible and beautiful. Identifiable by the correct hardware and the older Coach labels. One of the rare luxury American accessories." },
  { id:93, rank:93, name:"Johnston & Murphy Dress Shoe (1960s–70s, Goodyear Welt)", brand:"Johnston & Murphy", era:"1960s–70s", category:"Footwear", rarity:"rare", value:"$200–$700", findable:true, description:"Made in Nashville, Tennessee, with Goodyear welt construction. US presidents have worn Johnston & Murphy since Millard Fillmore. 60s–70s examples in full-grain leather with correct welt construction are significantly better than modern output." },
  { id:94, rank:94, name:"Lee Westerner Jacket (1970s, Corduroy)", brand:"H.D. Lee Co.", era:"1970s", category:"Other", rarity:"rare", value:"$150–$600", findable:true, description:"Lee's corduroy western jacket with the distinctive two-pocket Western styling. The 70s examples in wide-wale brown, tan, or rust are one of the more overlooked vintage categories — recognizable, wearable, and increasingly collectible." },
  { id:95, rank:95, name:"Stüssy Nylon Windbreaker (Early 1990s)", brand:"Stüssy", era:"1990s", category:"Streetwear", rarity:"rare", value:"$200–$800", findable:true, description:"Early 90s nylon windbreaker with the world tour graphics and Stüssy logo. From the era when Stüssy's Shawn Stussy was still involved and the brand was genuinely underground. One of streetwear's founding garments." },
  { id:96, rank:96, name:"Banana Republic Safari Jacket (1980s, Pre-Gap)", brand:"Banana Republic", era:"1980s", category:"Outerwear", rarity:"rare", value:"$150–$500", findable:true, description:"Before The Gap acquisition made Banana Republic a mall staple, it was a genuine travel and adventure clothing brand. The 80s safari jackets in cotton twill with the exotic-destination catalogs are a cult favorite." },
  { id:97, rank:97, name:"Polo Ralph Lauren Rugby Shirt (1990s)", brand:"Ralph Lauren", era:"1990s", category:"Shirts", rarity:"findable", value:"$60–$200", findable:true, description:"The heavyweight cotton rugby with the wide horizontal stripes and Polo embroidery. 90s examples in original cotton are significantly heavier than modern versions. A Brooklyn and Boston staple for decades." },
  { id:98, rank:98, name:"Levi's 517 Bootcut (1980s, USA Made)", brand:"Levi Strauss & Co.", era:"1980s", category:"Denim", rarity:"findable", value:"$60–$200", findable:true, description:"The US-made boot cut from the 80s. Less collectible than older iterations but the correct construction and Made in USA label make these worth seeking out. The western-wear crossover jean." },
  { id:99, rank:99, name:"Timberland 6-Inch Premium Boot (1990s, Made in USA)", brand:"Timberland", era:"1990s", category:"Footwear", rarity:"findable", value:"$100–$400", findable:true, description:"Made in New Hampshire before production moved offshore. The 90s US-made Timberland boot in the original wheat nubuck — iconic in hip-hop culture from Jay-Z to Wu-Tang — is significantly more durable than current production." },
  { id:100, rank:100, name:"Levi's Orange Tab Cord Trucker Jacket (1970s)", brand:"Levi Strauss & Co.", era:"1970s", category:"Other", rarity:"rare", value:"$150–$600", findable:true, description:"Levi's applied their Type III trucker template to corduroy with the orange tab in the 70s. Wide-wale in earthy tones. An underrated piece relative to the denim versions — and therefore still findable at reasonable prices." },
];

export const VINTAGE_CATEGORIES = ["All","Denim","Leather","Military","Workwear","Sportswear","Footwear","T-Shirts","Knitwear","Shirts","Outerwear","Streetwear","Designer","Accessories","Other"];
export const VINTAGE_ERAS = ["All","1930s–40s","1940s","1950s–60s","1960s","1970s","1980s","1990s","2000s","2010s"];
export const VINTAGE_RARITIES = ["All","findable","rare","very rare","holy grail"];

// ─────────────────────────────────────────────────────────────────────────────
// VINTAGE SHOPS (US cities only)
// ─────────────────────────────────────────────────────────────────────────────
export const VSTORES = [

  // ── BAY AREA ──────────────────────────────────────────────────────────────
  { id:1,  name:"Ver Unica", area:"bay", city:"San Francisco", address:"437B Hayes St, San Francisco, CA", specialty:"1920s–90s All", notes:"Hayes Valley institution. Curated floor-to-ceiling with everything from Victorian blouses to 80s nylon. One of the most respected vintage shops in California.", rating:4.7, phone:"(415) 431-0688", hours:"Mon–Sat 11am–7pm, Sun 12pm–6pm", website:"" },
  { id:2,  name:"Crossroads Trading", area:"bay", city:"San Francisco", address:"Multiple SF locations", specialty:"Contemporary Vintage / Resale", notes:"Best-priced curated resale in the city. Multiple locations — Haight, Castro, and Mission. High turnover means fresh stock constantly. The everyday digger's shop.", rating:4.3, phone:"", hours:"Daily 11am–8pm", website:"https://www.crossroadstrading.com" },
  { id:3,  name:"Schauplatz", area:"bay", city:"San Francisco", address:"791 Valencia St, San Francisco, CA", specialty:"European Vintage / Workwear", notes:"Mission District European vintage specialist. Strong on French workwear, moleskin, and continental denim. One of the few US shops with serious European blue-collar finds.", rating:4.6, phone:"(415) 864-5665", hours:"Wed–Sun 12pm–6pm", website:"" },
  { id:4,  name:"Wasteland", area:"bay", city:"San Francisco", address:"1660 Haight St, San Francisco, CA", specialty:"1970s–90s / Designer", notes:"The Haight's most consistent vintage shop. Good range of 70s–90s with occasional designer finds. High foot traffic means stock moves fast — visit often.", rating:4.3, phone:"(415) 863-3150", hours:"Mon–Sat 11am–8pm, Sun 12pm–7pm", website:"https://www.shopwasteland.com" },
  { id:5,  name:"Painted Bird", area:"bay", city:"San Francisco", address:"1899 Mission St, San Francisco, CA", specialty:"Curated / All eras", notes:"Mission Street curated vintage with a strong eye. The owner sources globally. One of the better shops for Japanese vintage finds in the Bay Area.", rating:4.6, phone:"", hours:"Wed–Sun 12pm–6pm", website:"" },
  { id:6,  name:"Mars Mercantile", area:"bay", city:"Oakland", address:"3905 Grand Ave, Oakland, CA", specialty:"1940s–80s Americana", notes:"Grand Avenue gem with deep Americana inventory. Workwear, denim, and military. One of Oakland's best sources for pre-1980 American clothing.", rating:4.7, phone:"(510) 601-0543", hours:"Tue–Sun 11am–6pm", website:"" },
  { id:7,  name:"Temescal Alley Vintage", area:"bay", city:"Oakland", address:"Temescal Alley, Oakland, CA", specialty:"Curated Contemporary", notes:"Multiple small vintage vendors in the Temescal Alley corridor. Good for weekend digging — quality varies by vendor but some real finds appear.", rating:4.4, phone:"", hours:"Sat–Sun 11am–5pm", website:"" },
  { id:8,  name:"Thrift Town", area:"bay", city:"San Francisco", address:"2101 Mission St, San Francisco, CA", specialty:"All / Thrift", notes:"The Bay Area's best true thrift. Massive floor space, low prices, and fast stock rotation. The serious digger's source — you have to work for it but the prices justify the effort.", rating:4.2, phone:"(415) 861-1132", hours:"Daily 9am–8pm", website:"" },

  // ── LOS ANGELES ───────────────────────────────────────────────────────────
  { id:9,  name:"Squaresville", area:"la", city:"Los Feliz", address:"4935 Hollywood Blvd, Los Angeles, CA", specialty:"1950s–80s Curated", notes:"The most personality-driven shop in LA. Eclectic, colorful, and deeply personal curation. Strong on 50s–60s dresses, 70s leisure, and 80s novelty. An experience as much as a shop.", rating:4.7, phone:"(323) 669-8464", hours:"Daily 11am–7pm", website:"" },
  { id:10, name:"Resurrection", area:"la", city:"Los Angeles", address:"8006 Melrose Ave, Los Angeles, CA", specialty:"High-End Designer Vintage", notes:"LA's finest high-end vintage — Halston, Ossie Clark, Gucci, Versace. The shop where stylists and costume designers source. Not for the budget shopper, but the quality is unmatched.", rating:4.8, phone:"(323) 651-5516", hours:"Mon–Sat 11am–7pm, Sun 12pm–6pm", website:"" },
  { id:11, name:"Jet Rag", area:"la", city:"Los Angeles", address:"825 N La Brea Ave, Los Angeles, CA", specialty:"$1 Sunday / All eras", notes:"$1 Sunday sale on the parking lot is a Los Angeles institution. Friday the racks are fresh and fully priced; by Sunday everything not sold is a dollar. The most democratic vintage in the city.", rating:4.5, phone:"(323) 939-0528", hours:"Mon–Sat 11am–7pm, Sun (parking lot sale) 9am–4pm", website:"" },
  { id:12, name:"American Rag Cie", area:"la", city:"Los Angeles", address:"150 S La Brea Ave, Los Angeles, CA", specialty:"All eras / International", notes:"La Brea landmark since 1984. Global vintage sourcing with a strong Japanese and European presence. Also sells new collections from emerging brands. A full lifestyle store built around vintage.", rating:4.5, phone:"(323) 935-3154", hours:"Mon–Sat 11am–8pm, Sun 11am–7pm", website:"" },
  { id:13, name:"The Way We Wore", area:"la", city:"Los Angeles", address:"334 S La Brea Ave, Los Angeles, CA", specialty:"1900s–1980s Couture / High End", notes:"Museum-quality vintage couture on La Brea. Ballgowns, beaded 20s dresses, Pucci, and Givenchy. The reference point for LA costume designers and serious collectors.", rating:4.9, phone:"(323) 937-0878", hours:"Mon–Sat 11am–6pm", website:"" },
  { id:14, name:"Playclothes", area:"la", city:"Los Angeles", address:"7277 Melrose Ave, Los Angeles, CA", specialty:"1940s–70s All", notes:"Melrose institution for decades. Strong on 40s–70s with excellent men's and women's selections. The kind of shop where you find something genuinely unexpected every visit.", rating:4.6, phone:"(323) 653-2860", hours:"Mon–Sat 11am–7pm", website:"" },
  { id:15, name:"Wasteland LA", area:"la", city:"Los Angeles", address:"7428 Melrose Ave, Los Angeles, CA", specialty:"1970s–2000s / Designer", notes:"Melrose flagship of the Wasteland chain. Stronger than the SF locations for 80s–90s and occasional designer finds. Fast turnover — the Melrose foot traffic keeps stock moving.", rating:4.3, phone:"(323) 653-3028", hours:"Mon–Sat 11am–8pm, Sun 12pm–7pm", website:"https://www.shopwasteland.com" },
  { id:16, name:"Mohawk General Store", area:"la", city:"Los Angeles", address:"4011 W Sunset Blvd, Los Angeles, CA", specialty:"Japanese Vintage / Contemporary", notes:"The Silver Lake shop that bridges Japanese workwear, vintage denim, and contemporary brands. Owner Kevin Carney has the best taste in LA. Where the Gold Line bar's sound system came from.", rating:4.8, phone:"(323) 669-1601", hours:"Mon–Sat 11am–7pm, Sun 12pm–6pm", website:"" },
  { id:17, name:"Swords Smith", area:"la", city:"Los Angeles", address:"4533 Hollywood Blvd, Los Angeles, CA", specialty:"Workwear / Military / Japanese", notes:"Hollywood Boulevard's best curated vintage. Serious workwear, military, and Japanese selvedge. For the collector who knows what they're looking for.", rating:4.7, phone:"(323) 665-6693", hours:"Mon–Sat 11am–7pm", website:"" },
  { id:18, name:"Goodwill Outlet (The Bins)", area:"la", city:"Los Angeles", address:"Multiple LA locations", specialty:"All / By weight", notes:"The ultimate dig — sold by the pound, not by the piece. Requires patience, a strong stomach, and good instincts. The source for everything the better thrift stores pass over.", rating:4.1, phone:"", hours:"Daily 9am–6pm", website:"" },

  // ── SEATTLE ───────────────────────────────────────────────────────────────
  { id:19, name:"Fritzi Ritz", area:"seattle", city:"Seattle", address:"3425 Fremont Pl N, Seattle, WA", specialty:"1940s–80s Women's", notes:"Fremont's beloved women's vintage specialist since 1983. Strong on mid-century silhouettes, 60s shifts, and 70s wrap dresses. Seattle's most consistent source for feminine vintage.", rating:4.6, phone:"(206) 633-0929", hours:"Tue–Sun 11am–6pm", website:"" },
  { id:20, name:"Red Light Vintage", area:"seattle", city:"Seattle", address:"312 Broadway E, Seattle, WA", specialty:"All eras / All", notes:"Capitol Hill's largest vintage shop. Three floors of mixed vintage from all eras. The go-to for Seattle's costume designers and stylists. Strong on 70s–90s with good workwear and military.", rating:4.5, phone:"(206) 329-2200", hours:"Mon–Sat 11am–8pm, Sun 11am–7pm", website:"" },
  { id:21, name:"Isadora's Antique Clothing", area:"seattle", city:"Seattle", address:"1915 1st Ave, Seattle, WA", specialty:"Antique / Victorian–1960s", notes:"Pike Place Market area antique clothing specialist. Victorian through early 60s. One of the few shops in Seattle that genuinely specializes in pre-1960s clothing.", rating:4.6, phone:"(206) 441-7711", hours:"Mon–Sat 11am–5pm", website:"" },
  { id:22, name:"Dagmar Vintage", area:"seattle", city:"Seattle", address:"915 E Pike St, Seattle, WA", specialty:"Curated / 1960s–80s", notes:"Capitol Hill curated vintage with a strong eye for quality over quantity. Fewer pieces, better pieces. Good for 60s mod, 70s earth tones, and early 80s designer.", rating:4.5, phone:"", hours:"Wed–Sun 12pm–6pm", website:"" },
  { id:23, name:"Seattle Goodwill Outlet", area:"seattle", city:"Seattle", address:"Multiple Seattle locations", specialty:"All / By weight", notes:"The Pacific Northwest bins. Seattle's thriving vintage culture means items cycle through quickly. Patience rewarded. The best deals in the region for the dedicated digger.", rating:4.1, phone:"", hours:"Daily 9am–7pm", website:"" },

  // ── PORTLAND ──────────────────────────────────────────────────────────────
  { id:24, name:"House of Vintage", area:"portland", city:"Portland", address:"3315 SE Belmont St, Portland, OR", specialty:"All eras / 60+ vendors", notes:"Portland's largest vintage market — over 60 vendors under one roof on Belmont Street. Something for everyone from every era. A full afternoon destination. The heartbeat of Portland's vintage scene.", rating:4.6, phone:"(503) 235-1743", hours:"Daily 11am–7pm", website:"" },
  { id:25, name:"Decades Vintage", area:"portland", city:"Portland", address:"3518 SE Hawthorne Blvd, Portland, OR", specialty:"1960s–80s Curated", notes:"Hawthorne's most consistent vintage shop. Tightly edited selection with a strong emphasis on quality. Good for 60s–70s women's and 70s–80s men's workwear and sportswear.", rating:4.6, phone:"(503) 239-1093", hours:"Daily 11am–7pm", website:"" },
  { id:26, name:"Stars Antique Mall", area:"portland", city:"Portland", address:"7027 SE Milwaukie Ave, Portland, OR", specialty:"Antique / All eras", notes:"Massive antique mall on Milwaukie with multiple vintage clothing vendors alongside furniture and decor. The closest thing Portland has to a true flea market experience indoors.", rating:4.3, phone:"(503) 239-0346", hours:"Daily 11am–6pm", website:"" },
  { id:27, name:"Artifact: Creative Recycle", area:"portland", city:"Portland", address:"3520 SE Hawthorne Blvd, Portland, OR", specialty:"Curated / Workwear / Military", notes:"Hawthorne's workwear and military specialist. One of Portland's best sources for Carhartt, canvas, and denim from the correct eras. Small, focused, and consistent.", rating:4.5, phone:"", hours:"Wed–Sun 12pm–6pm", website:"" },
  { id:28, name:"Cry Baby Vintage", area:"portland", city:"Portland", address:"3432 SE Hawthorne Blvd, Portland, OR", specialty:"1970s–90s / Colorful", notes:"Hawthorne's most colorful shop. Specializes in brighter, bolder 70s–90s pieces — tropical shirts, statement pieces, and fun vintage that most shops overlook.", rating:4.5, phone:"", hours:"Tue–Sun 11am–6pm", website:"" },

  // ── CHICAGO ───────────────────────────────────────────────────────────────
  { id:29, name:"Strange Cargo", area:"chicago", city:"Chicago", address:"3448 N Clark St, Chicago, IL", specialty:"1950s–90s / T-Shirts", notes:"Wrigleyville vintage institution since 1985. Massive t-shirt wall is the main event — original single-stitch band tees, sports tees, and novelty tees at reasonable prices. Also strong on denim.", rating:4.6, phone:"(773) 327-8090", hours:"Mon–Sat 11am–7pm, Sun 12pm–6pm", website:"" },
  { id:30, name:"Ragstock", area:"chicago", city:"Chicago", address:"812 W Belmont Ave, Chicago, IL", specialty:"All / Bulk Vintage", notes:"The Midwest chain's Chicago locations are particularly well-stocked. By-the-pound sections and curated racks side by side. Good prices and high turnover.", rating:4.2, phone:"(773) 975-0640", hours:"Mon–Sat 11am–8pm, Sun 12pm–7pm", website:"https://www.ragstock.com" },
  { id:31, name:"Knee Deep Vintage", area:"chicago", city:"Chicago", address:"4013 N Milwaukee Ave, Chicago, IL", specialty:"Workwear / Denim / Military", notes:"Logan Square's workwear specialist. One of the best shops in the Midwest for Carhartt, military surplus, and selvedge denim. Owner sources nationally.", rating:4.7, phone:"", hours:"Tue–Sun 12pm–7pm", website:"" },
  { id:32, name:"Wicker Park Bucktown Vintage", area:"chicago", city:"Chicago", address:"Multiple Wicker Park locations", specialty:"All eras", notes:"The Wicker Park / Bucktown corridor has a concentration of vintage shops within walking distance. The neighborhood's foot traffic and demographics make for strong, fast-rotating stock.", rating:4.4, phone:"", hours:"Daily 11am–7pm", website:"" },
  { id:33, name:"Hollywood Mirror", area:"chicago", city:"Chicago", address:"812 W Belmont Ave, Chicago, IL", specialty:"1950s–80s / Costumes", notes:"Belmont Avenue institution known for both authentic vintage and costume hire. The largest selection of 50s–80s formalwear in Chicago. A reference point for the city's vintage community.", rating:4.4, phone:"(773) 404-4510", hours:"Mon–Sat 11am–7pm, Sun 12pm–6pm", website:"" },
  { id:34, name:"Wooly Mammoth", area:"chicago", city:"Chicago", address:"3745 N Lincoln Ave, Chicago, IL", specialty:"Workwear / Denim / Heritage", notes:"Lincoln Square heritage specialist. One of Chicago's finest sources for pre-1980 American workwear and denim. Small, curated, and deeply knowledgeable staff.", rating:4.7, phone:"(773) 296-6300", hours:"Mon–Sat 11am–7pm, Sun 12pm–6pm", website:"" },

  // ── NEW YORK ──────────────────────────────────────────────────────────────
  { id:35, name:"What Goes Around Comes Around", area:"nyc", city:"New York", address:"351 W Broadway, New York, NY", specialty:"High-End Designer Vintage", notes:"SoHo's most famous luxury vintage. Chanel, Levi's, and everything between. Expensive, but the curation and provenance are unmatched. A reference point for the global vintage market.", rating:4.6, phone:"(212) 343-1225", hours:"Mon–Sat 11am–8pm, Sun 12pm–7pm", website:"https://www.whatgoesaroundnyc.com" },
  { id:36, name:"Beacon's Closet", area:"nyc", city:"Brooklyn", address:"74 Guernsey St, Brooklyn, NY", specialty:"All eras / Consignment", notes:"Greenpoint's beloved vintage and consignment shop. The best prices for quality vintage in New York. Multiple locations — Greenpoint and Park Slope. High turnover, fair pricing.", rating:4.5, phone:"(718) 486-0816", hours:"Mon–Fri 11am–8pm, Sat–Sun 11am–7pm", website:"https://www.beaconscloset.com" },
  { id:37, name:"Screaming Mimi's", area:"nyc", city:"New York", address:"240 W 14th St, New York, NY", specialty:"1940s–90s Curated", notes:"Chelsea vintage institution since 1978. Strong on 40s–70s with excellent sportswear and workwear. The staff's knowledge is exceptional — ask for help. One of New York's finest.", rating:4.7, phone:"(212) 677-6464", hours:"Mon–Sat 12pm–8pm, Sun 1pm–7pm", website:"" },
  { id:38, name:"Ina NYC", area:"nyc", city:"New York", address:"15 Bleecker St, New York, NY", specialty:"Designer Consignment / Vintage", notes:"New York's top consignment destination for designer vintage. Multiple locations. Strong on 80s–90s European designer and Japanese archive pieces. The shop where serious collectors sell.", rating:4.5, phone:"(212) 228-8511", hours:"Mon–Sat 11am–8pm, Sun 12pm–7pm", website:"" },
  { id:39, name:"L Train Vintage", area:"nyc", city:"Brooklyn", address:"Multiple Brooklyn locations", specialty:"All / Affordable", notes:"Multiple Brooklyn locations with by-the-pound pricing. The best entry point into NYC vintage for budget diggers. Bushwick, Williamsburg, and Bed-Stuy locations all have different stock profiles.", rating:4.3, phone:"", hours:"Daily 11am–8pm", website:"https://www.ltrainvintage.com" },
  { id:40, name:"10 Ft Single by Stella Dallas", area:"nyc", city:"Brooklyn", address:"285 N 6th St, Brooklyn, NY", specialty:"1970s–90s / Women's", notes:"Williamsburg women's vintage specialist with an exceptional 70s–90s selection. Particularly strong on 80s designer and NY label pieces. A neighborhood institution.", rating:4.6, phone:"(718) 486-9487", hours:"Daily 12pm–8pm", website:"" },
  { id:41, name:"Amarcord Vintage Fashion", area:"nyc", city:"New York", address:"252 Lafayette St, New York, NY", specialty:"Italian / European Designer Vintage", notes:"NoLIta's Italian vintage specialist. Moschino, Versace, Armani, and Ferragamo in depth. The best source in New York for Italian designer archive pieces.", rating:4.7, phone:"(212) 431-4161", hours:"Mon–Sat 11am–8pm, Sun 12pm–7pm", website:"" },
  { id:42, name:"Rough Trade (Vintage Section)", area:"nyc", city:"Brooklyn", address:"64 N 9th St, Brooklyn, NY", specialty:"Music Adjacent / 1970s–90s", notes:"Already in the shops list, but Rough Trade's small vintage section curated for the music crowd is worth noting — band tees, 70s rock wear, and music-adjacent pieces.", rating:4.5, phone:"", hours:"Mon–Sat 11am–9pm, Sun 11am–8pm", website:"" },
  { id:43, name:"Chelsea Flea Market", area:"nyc", city:"New York", address:"West 25th St, New York, NY", specialty:"All / Market", notes:"Saturday and Sunday outdoor market with multiple vintage vendors. The original NYC flea market experience. Stock quality varies wildly but the finds justify the patience.", rating:4.3, phone:"", hours:"Sat–Sun 9am–5pm", website:"" },

  // ── AUSTIN ────────────────────────────────────────────────────────────────
  { id:44, name:"Prototype Vintage", area:"austin", city:"Austin", address:"1700 S Congress Ave, Austin, TX", specialty:"1960s–90s Curated", notes:"South Congress Avenue's finest vintage. The curation rivals anything in NYC or LA. Strong on 70s–80s with excellent denim, workwear, and sportswear. Austin's most consistent shop.", rating:4.7, phone:"(512) 804-4578", hours:"Mon–Sat 11am–7pm, Sun 12pm–6pm", website:"" },
  { id:45, name:"Blue Velvet Vintage", area:"austin", city:"Austin", address:"1204 S Congress Ave, Austin, TX", specialty:"1950s–80s / Women's", notes:"SoCo women's vintage specialist with a strong mid-century sensibility. Great for 50s–60s dresses and 70s Boho. One of Austin's most photogenic shops.", rating:4.5, phone:"(512) 326-3332", hours:"Mon–Sun 11am–7pm", website:"" },
  { id:46, name:"Charm School Vintage", area:"austin", city:"Austin", address:"2900 E 2nd St, Austin, TX", specialty:"All eras / East Austin", notes:"East Austin's most community-oriented vintage shop. Regular events and a welcoming atmosphere alongside strong inventory. Good for 70s–90s at fair prices.", rating:4.6, phone:"(512) 585-4085", hours:"Tue–Sun 11am–6pm", website:"" },
  { id:47, name:"Blackmail Boutique", area:"austin", city:"Austin", address:"1202 S Congress Ave, Austin, TX", specialty:"Dark / Gothic / Punk Vintage", notes:"The darkest shop on SoCo. Black clothing, leather, and vintage punk and goth. A necessary counterpoint to the mainstream vintage shops nearby.", rating:4.4, phone:"(512) 326-7670", hours:"Daily 11am–7pm", website:"" },
  { id:48, name:"By George", area:"austin", city:"Austin", address:"524 N Lamar Blvd, Austin, TX", specialty:"Designer / Contemporary", notes:"Austin's longstanding designer and contemporary boutique with a strong vintage component. The bridge between Austin's vintage culture and the designer world.", rating:4.5, phone:"(512) 472-5951", hours:"Mon–Sat 10am–6pm", website:"" },
];

export const VSTORE_AREAS = [
  { key:"all",      label:"ALL" },
  { key:"bay",      label:"BAY AREA" },
  { key:"la",       label:"LOS ANGELES" },
  { key:"seattle",  label:"SEATTLE" },
  { key:"portland", label:"PORTLAND" },
  { key:"chicago",  label:"CHICAGO" },
  { key:"nyc",      label:"NEW YORK" },
  { key:"austin",   label:"AUSTIN" },
];
